/* Ecobella v2: visual prototype only. All records below are invented. */
(() => {
  'use strict';
  const KEY = 'ecobella-v2-demo-2026-09';
  const TODAY = '2026-09-28';
  const clients = [
    {id:'c1',name:'Marina Azevedo',phone:'(00) 00000-0001',email:'marina@example.test',status:'Ativa',since:'2025-03-18',notes:'Prefere horários no início da manhã.'},
    {id:'c2',name:'Rafael Monteiro',phone:'(00) 00000-0002',email:'rafael@example.test',status:'Ativo',since:'2025-08-07',notes:'Aulas aos sábados.'},
    {id:'c3',name:'Lívia Costa',phone:'(00) 00000-0003',email:'livia@example.test',status:'Ativa',since:'2026-01-12',notes:'Primeira experiência com equitação.'},
    {id:'c4',name:'Pedro Nascimento',phone:'(00) 00000-0004',email:'pedro@example.test',status:'Ativo',since:'2024-11-02',notes:'Interesse em salto.'},
    {id:'c5',name:'Isabela Rocha',phone:'(00) 00000-0005',email:'isabela@example.test',status:'Ativa',since:'2026-04-25',notes:'Horários de terça e quinta.'},
    {id:'c6',name:'André Martins',phone:'(00) 00000-0006',email:'andre@example.test',status:'Inativo',since:'2025-01-06',notes:'Cadastro inativo a pedido do cliente.'}
  ];
  const horses = [
    {id:'h1',name:'Gaia',breed:'Brasileiro de Hipismo',owner:'Haras Ecobella',status:'Ativa',level:'Intermediário',restriction:'Descanso após sessões de salto.'},
    {id:'h2',name:'Trovão',breed:'Mangalarga Marchador',owner:'Haras Ecobella',status:'Ativo',level:'Iniciante',restriction:'Nenhuma registrada.'},
    {id:'h3',name:'Safira',breed:'Lusitano',owner:'Clara Almeida',status:'Ativa',level:'Avançado',restriction:'Evitar sessões em dias consecutivos.'},
    {id:'h4',name:'Bento',breed:'Quarto de Milha',owner:'Haras Ecobella',status:'Em descanso',level:'Iniciante',restriction:'Descanso informado pela equipe; confirmar disponibilidade.'}
  ];
  const team = [
    {id:'t1',name:'Ana Beatriz Lima',role:'Instrutora',phone:'(00) 00000-0011',status:'Ativa',capacity:'8h / dia',note:'Equitação básica e intermediária.'},
    {id:'t2',name:'Caio Ferreira',role:'Instrutor',phone:'(00) 00000-0012',status:'Ativo',capacity:'8h / dia',note:'Salto e treinamento técnico.'},
    {id:'t3',name:'Júlia Almeida',role:'Administrativo',phone:'(00) 00000-0013',status:'Ativa',capacity:'—',note:'Planejamento de grade e pagamentos.'},
    {id:'t4',name:'Sofia Mendes',role:'Gerente',phone:'(00) 00000-0014',status:'Ativa',capacity:'—',note:'Coordenação operacional.'}
  ];
  const campaigns = [
    {id:'m1',name:'Primeira experiência',offer:'Aula experimental gratuita',start:'2026-09-01',end:'2026-10-31',status:'Em andamento',contacts:42,conversions:9,description:'Contato com interessados que ainda não realizaram aula experimental. A conversão aqui é um agendamento confirmado, não receita.'},
    {id:'m2',name:'Volta às aulas',offer:'Convite para retomar aulas regulares',start:'2026-08-01',end:'2026-08-31',status:'Encerrada',contacts:31,conversions:7,description:'Reativação de clientes sem aula recente. A conversão é o retorno agendado.'},
    {id:'m3',name:'Semana do cavalo',offer:'Apresentação das modalidades',start:'2026-10-05',end:'2026-10-18',status:'Programada',contacts:18,conversions:2,description:'Convite antecipado. A conversão contabiliza contatos que já confirmaram uma visita.'}
  ];
  const seed = {
    classes:[
      {id:'a1',date:'2026-09-28',time:'08:00',duration:60,type:'Equitação básica',instructor:'t1',clientIds:['c1'],horse:'h2',status:'planned',series:'s1',charges:{c1:180},paid:{c1:180}},
      {id:'a2',date:'2026-09-28',time:'09:30',duration:60,type:'Salto',instructor:'t2',clientIds:['c2','c4'],horse:'h3',status:'planned',series:'s2',charges:{c2:220,c4:220},paid:{c2:220,c4:0}},
      {id:'a3',date:'2026-09-28',time:'14:00',duration:45,type:'Experimental',instructor:'t1',clientIds:['c3'],horse:'h1',status:'planned',series:null,trial:true,charges:{c3:0},paid:{c3:0}},
      {id:'a4',date:'2026-09-29',time:'08:00',duration:60,type:'Equitação básica',instructor:'t1',clientIds:['c5'],horse:'h2',status:'planned',series:'s3',charges:{c5:180},paid:{c5:0}},
      {id:'a5',date:'2026-09-29',time:'10:00',duration:60,type:'Salto',instructor:'t2',clientIds:['c4'],horse:'h3',status:'planned',series:'s4',charges:{c4:220},paid:{c4:220}},
      {id:'a6',date:'2026-09-30',time:'11:00',duration:60,type:'Equitação básica',instructor:'t1',clientIds:['c1','c5'],horse:'h1',status:'planned',series:'s5',charges:{c1:180,c5:180},paid:{c1:180,c5:90}},
      {id:'a7',date:'2026-10-01',time:'15:00',duration:60,type:'Adestramento',instructor:'t2',clientIds:['c2'],horse:'h3',status:'planned',series:'s6',charges:{c2:200},paid:{c2:0}},
      {id:'a8',date:'2026-10-02',time:'09:00',duration:60,type:'Equitação básica',instructor:'t1',clientIds:['c1'],horse:'h2',status:'planned',series:'s1',charges:{c1:180},paid:{c1:180}},
      {id:'a9',date:'2026-09-25',time:'08:00',duration:60,type:'Equitação básica',instructor:'t1',clientIds:['c1'],horse:'h2',status:'done',series:'s1',charges:{c1:180},paid:{c1:180}},
      {id:'a10',date:'2026-09-24',time:'10:00',duration:60,type:'Salto',instructor:'t2',clientIds:['c2'],horse:'h3',status:'done',series:'s2',charges:{c2:220},paid:{c2:220}},
      {id:'a11',date:'2026-09-23',time:'09:00',duration:45,type:'Experimental',instructor:'t1',clientIds:['c5'],horse:'h1',status:'done',series:null,trial:true,charges:{c5:0},paid:{c5:0}},
      {id:'a12',date:'2026-09-22',time:'08:00',duration:60,type:'Equitação básica',instructor:'t1',clientIds:['c4'],horse:'h2',status:'cancelled',reason:'Chuva',series:'s3',charges:{c4:180},paid:{c4:0}},
      {id:'a13',date:'2026-10-05',time:'08:00',duration:60,type:'Equitação básica',instructor:'t1',clientIds:['c1'],horse:'h2',status:'planned',series:'s1',charges:{c1:180},paid:{c1:0}},
      {id:'a14',date:'2026-10-06',time:'10:00',duration:60,type:'Salto',instructor:'t2',clientIds:['c2','c4'],horse:'h3',status:'planned',series:'s2',charges:{c2:220,c4:220},paid:{c2:0,c4:0}}
    ],
    payments:[
      {id:'p1',date:'2026-09-22',clientId:'c1',classId:'a1',amount:180,method:'Pix',receipt:'comprovante-ficticio-001.pdf',status:'Registrado',installments:1},
      {id:'p2',date:'2026-09-24',clientId:'c2',classId:'a2',amount:220,method:'Cartão',receipt:'comprovante-ficticio-002.pdf',status:'Registrado',installments:2},
      {id:'p3',date:'2026-09-23',clientId:'c4',classId:'a5',amount:220,method:'Pix',receipt:'comprovante-ficticio-003.pdf',status:'Registrado',installments:1},
      {id:'p4',date:'2026-09-26',clientId:'c1',classId:'a6',amount:180,method:'Pix',receipt:'comprovante-ficticio-004.pdf',status:'Registrado',installments:1},
      {id:'p5',date:'2026-09-26',clientId:'c5',classId:'a6',amount:90,method:'Dinheiro',receipt:'comprovante-ficticio-005.pdf',status:'Registrado',installments:1},
      {id:'p6',date:'2026-09-26',clientId:'c1',classId:'a8',amount:180,method:'Pix',receipt:'comprovante-ficticio-006.pdf',status:'Registrado',installments:1},
      {id:'p7',date:'2026-09-20',clientId:'c1',classId:'a9',amount:180,method:'Pix',receipt:'comprovante-ficticio-007.pdf',status:'Registrado',installments:1},
      {id:'p8',date:'2026-09-20',clientId:'c2',classId:'a10',amount:220,method:'Cartão',receipt:'comprovante-ficticio-008.pdf',status:'Registrado',installments:1}
    ]
  };
  let data;
  try { data = JSON.parse(localStorage.getItem(KEY)) || structuredClone(seed); if (!Array.isArray(data.classes) || !Array.isArray(data.payments)) throw Error(); }
  catch { data = structuredClone(seed); }
  const state = {page:'agenda',view:'semana',date:TODAY,filters:{},tab:'Dados'};
  const $ = (sel,root=document) => root.querySelector(sel);
  const themePreference = matchMedia('(prefers-color-scheme: dark)');
  function setTheme(theme, persist = false) {
    document.documentElement.dataset.theme = theme;
    $('meta[name="theme-color"]').content = theme === 'dark' ? '#121820' : '#ffffff';
    const label = theme === 'dark' ? 'Ativar tema claro' : 'Ativar tema escuro';
    const button = $('#theme-toggle');
    button.setAttribute('aria-label', label);
    button.title = label;
    button.textContent = theme === 'dark' ? '☀' : '☾';
    if (persist) localStorage.setItem('ecobella-v2-theme', theme);
  }
  setTheme(document.documentElement.dataset.theme);
  $('#theme-toggle').addEventListener('click', () => {
    setTheme(document.documentElement.dataset.theme === 'dark' ? 'light' : 'dark', true);
  });
  themePreference.addEventListener('change', e => {
    if (!localStorage.getItem('ecobella-v2-theme')) setTheme(e.matches ? 'dark' : 'light');
  });
  const esc = x => String(x ?? '').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const fmtDate = (d,opts={day:'2-digit',month:'short',year:'numeric'}) => new Date(d+'T12:00:00').toLocaleDateString('pt-BR',opts);
  const fmtMoney = n => Number(n).toLocaleString('pt-BR',{style:'currency',currency:'BRL'});
  const lookup = (arr,id) => arr.find(x=>x.id===id);
  const addDays = (iso,n) => {const d=new Date(iso+'T12:00:00');d.setDate(d.getDate()+n);return d.toISOString().slice(0,10)};
  const weekStart = iso => {const d=new Date(iso+'T12:00:00');return addDays(iso,-((d.getDay()+6)%7))};
  const monthStart = iso => iso.slice(0,7)+'-01';
  const monthShift = (iso,n) => {const d=new Date(iso+'T12:00:00');d.setDate(1);d.setMonth(d.getMonth()+n);return d.toISOString().slice(0,10)};
  const classSort=(a,b)=>(a.date+' '+a.time).localeCompare(b.date+' '+b.time);
  const classFinancial = (a,clientId) => a.trial?'trial':clientId?((a.paid[clientId]||0)>=(a.charges[clientId]||0)?'paid':(a.paid[clientId]||0)>0?'partial':'pending'):a.clientIds.every(id=>(a.paid[id]||0)>=(a.charges[id]||0))?'paid':a.clientIds.some(id=>(a.paid[id]||0)>0)?'partial':'pending';
  const statusLabel={planned:'Planejada',done:'Concluída',cancelled:'Cancelada',paid:'Paga',partial:'Parcial',pending:'Pendente',trial:'Experimental'};
  const badge=(label,kind)=>`<span class="badge ${esc(kind||'')}">${esc(label)}</span>`;
  const clientName=id=>lookup(clients,id)?.name||'Cliente';
  const instructorName=id=>lookup(team,id)?.name||'A definir';
  const horseName=id=>lookup(horses,id)?.name||'A definir';
  const save=()=>localStorage.setItem(KEY,JSON.stringify(data));
  const navItems=[['dashboard','Dashboard','▥'],['agenda','Agenda','▦'],['aulas','Aulas','◫'],['clientes','Clientes','♙'],['cavalos','Cavalos','♞'],['equipe','Equipe','♧'],['campanhas','Campanhas','◈'],['pagamentos','Pagamentos','▤']];
  const navPaths={dashboard:'<rect x="3" y="3" width="7" height="7" rx="1"/><rect x="14" y="3" width="7" height="7" rx="1"/><rect x="3" y="14" width="7" height="7" rx="1"/><rect x="14" y="14" width="7" height="7" rx="1"/>',agenda:'<rect x="3" y="5" width="18" height="16" rx="2"/><path d="M7 3v4m10-4v4M3 10h18"/>',aulas:'<rect x="4" y="3" width="16" height="18" rx="2"/><path d="M8 8h8M8 12h8M8 16h5"/>',clientes:'<circle cx="9" cy="8" r="3"/><path d="M3 20v-2a6 6 0 0 1 12 0v2M17 5a3 3 0 0 1 0 6m1 4a5 5 0 0 1 3 5"/>',cavalos:'<path d="M5 21V9l4-6 3 3 5 1 2 5-3 3H9v6M9 15l-3-2m7-5h.01"/>',equipe:'<circle cx="9" cy="7" r="3"/><path d="M3 20v-2a6 6 0 0 1 12 0v2M17 7h5m-2.5-2.5v5"/>',campanhas:'<path d="M3 10v4h4l11 5V5L7 10H3Zm4 4 2 6h3l-2-5M20 10l2-2m-2 6 2 2"/>',pagamentos:'<rect x="2" y="5" width="20" height="14" rx="2"/><path d="M2 10h20M6 15h5"/>'};
  const icon=id=>`<svg viewBox="0 0 24 24" width="19" height="19" fill="none" stroke="currentColor" stroke-width="1.7" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">${navPaths[id]}</svg>`;
  function notify(msg){const t=$('#toast');t.textContent=msg;t.classList.add('show');clearTimeout(notify.timer);notify.timer=setTimeout(()=>t.classList.remove('show'),3500)}
  function head(title,subtitle,actions='',eyebrow='OPERAÇÃO'){return `<div class="page-head"><div><div class="eyebrow">${eyebrow}</div><h1>${title}</h1><p class="subtle">${subtitle}</p></div><div class="head-actions">${actions}</div></div>`}
  function route(page,params={}){const q=new URLSearchParams(params);location.hash=page+(q.size?'?'+q:''); if(location.hash==='#'+page&&!q.size)render()}
  function parseRoute(){const hash=location.hash.slice(1)||'agenda';const [page,query='']=hash.split('?');return {page:navItems.some(x=>x[0]===page)?page:'agenda',query:new URLSearchParams(query)}}
  function render(){const r=parseRoute();state.page=r.page;$('#nav').innerHTML=navItems.map((n,i)=>`${i===6?'<div class="nav-gap" aria-hidden="true"></div>':''}<a href="#${n[0]}" class="nav-link ${r.page===n[0]?'active':''}" ${r.page===n[0]?'aria-current="page"':''}><span class="nav-icon" aria-hidden="true">${icon(n[0])}</span>${n[1]}</a>`).join('');$('#breadcrumb').innerHTML=`Ecobella &nbsp;/&nbsp; <strong>${navItems.find(n=>n[0]===r.page)[1]}</strong>`;$('#sidebar').classList.remove('open');$('#menu-toggle').setAttribute('aria-expanded','false');
    const renderers={dashboard,agenda,aulas,clientes,cavalos,equipe,campanhas,pagamentos};$('#main').innerHTML=renderers[r.page](r.query);document.title=navItems.find(n=>n[0]===r.page)[1]+' · Ecobella v2';bindPage();}
  function csv(name,headers,rows){const content='\uFEFF'+[headers,...rows].map(row=>row.map(v=>'"'+String(v??'').replace(/"/g,'""')+'"').join(';')).join('\r\n');const url=URL.createObjectURL(new Blob([content],{type:'text/csv;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download=name;document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),1000);notify('CSV fictício exportado.');}
  function filteredClasses(){const f=state.filters;return data.classes.filter(a=>(!f.search||`${a.type} ${a.clientIds.map(clientName).join(' ')} ${instructorName(a.instructor)}`.toLocaleLowerCase('pt-BR').includes(f.search.toLocaleLowerCase('pt-BR')))&&(!f.client||a.clientIds.includes(f.client))&&(!f.recurrence||f.recurrence===(a.series?'yes':'no'))&&(!f.status||a.status===f.status)&&(!f.fromDate||a.date>=f.fromDate)&&(!f.finance||(f.finance==='due'?['pending','partial'].includes(classFinancial(a,f.client)):classFinancial(a,f.client)===f.finance))).sort((a,b)=>classSort(b,a))}
  function rowClass(a){const fin=classFinancial(a,state.filters.client);return `<tr><td><button class="row-action" data-detail="class:${a.id}">${fmtDate(a.date)}<span class="secondary">${a.time} · ${a.duration} min</span></button></td><td><strong>${esc(a.type)}</strong><span class="secondary">${a.series?'Recorrente':'Avulsa'}</span></td><td>${a.clientIds.map(id=>`<span>${esc(clientName(id))}</span>`).join('<br>')}</td><td>${esc(instructorName(a.instructor))}</td><td>${badge(statusLabel[a.status],a.status)}</td><td>${badge(statusLabel[fin],fin)}</td><td><button class="text-link" data-detail="class:${a.id}">Abrir →</button></td></tr>`}
  function table(headers,body,foot=''){return `<div class="table-wrap"><table class="data-table"><thead><tr>${headers.map(h=>`<th scope="col">${h}</th>`).join('')}</tr></thead><tbody>${body||`<tr><td colspan="${headers.length}"><div class="empty"><strong>Nenhum resultado neste recorte</strong>Ajuste os filtros para ver outros registros fictícios.</div></td></tr>`}</tbody></table></div>${foot?`<div class="table-foot">${foot}</div>`:''}`}
  function options(items,selected='',label='Todos'){return `<option value="">${label}</option>`+items.map(([v,l])=>`<option value="${esc(v)}" ${selected===v?'selected':''}>${esc(l)}</option>`).join('')}
  function dashboard(){const day=data.classes.filter(a=>a.date===TODAY).sort(classSort);const upcoming=data.classes.filter(a=>a.date>=TODAY&&a.status==='planned');const pending=upcoming.filter(a=>classFinancial(a)==='pending'||classFinancial(a)==='partial');const paid=upcoming.filter(a=>classFinancial(a)==='paid');const delivered=data.classes.filter(a=>a.status==='done');let byDay=[0,1,2,3,4,5,6].map(n=>data.classes.filter(a=>a.date===addDays(TODAY,n)&&a.status!=='cancelled').length);
    return head('Visão do haras',`Segunda-feira, ${fmtDate(TODAY,{day:'numeric',month:'long',year:'numeric'})} · aulas e cobranças dos dados fictícios.`,`<button class="button primary" data-new-class>＋ Nova aula</button>`,'PAINEL')+
    `<div class="metrics"><div class="panel metric clickable" data-go="agenda"><span class="label">Aulas hoje</span><div class="number">${day.length}</div><div class="meta">${day.filter(a=>a.status==='planned').length} planejadas · abrir agenda →</div></div><div class="panel metric clickable" data-go="aulas" data-upcoming><span class="label">Próximas aulas</span><div class="number">${upcoming.length}</div><div class="meta">A partir de 28 set · ver aulas →</div></div><div class="panel metric clickable" data-go="aulas" data-finance="due"><span class="label">Com pendência financeira</span><div class="number">${pending.length}</div><div class="meta">Aulas planejadas · conferir →</div></div><div class="panel metric clickable" data-go="aulas" data-finance="paid"><span class="label">Liberadas por pagamento</span><div class="number">${paid.length}</div><div class="meta">Aulas planejadas · conferir →</div></div></div>
    <div class="two-col"><div class="stack"><section class="panel"><div class="panel-head"><h2>Agenda de hoje</h2><button class="text-link" data-go="agenda">Abrir agenda →</button></div><div class="plain-list">${day.map(a=>`<div class="list-item"><span class="time-chip">${a.time}</span><div class="grow"><strong>${esc(a.type)} · ${a.clientIds.map(clientName).map(esc).join(', ')}</strong><small>${esc(instructorName(a.instructor))} · ${esc(horseName(a.horse))}</small></div>${badge(statusLabel[classFinancial(a)],classFinancial(a))}<button class="text-link" data-detail="class:${a.id}" aria-label="Abrir aula ${esc(a.type)}">→</button></div>`).join('')||'<div class="empty">Nenhuma aula hoje.</div>'}</div></section>
      <section class="panel"><div class="panel-head"><h2>Aulas nos próximos 7 dias</h2><span class="subtle">${byDay.reduce((a,b)=>a+b,0)} planejadas/concluídas</span></div><div class="panel-body"><div class="bar-chart">${byDay.map((n,i)=>`<div class="bar-col"><div class="bar" style="height:${Math.max(4,n*27)}px" title="${n} aulas"></div><span>${fmtDate(addDays(TODAY,i),{weekday:'short'})}</span></div>`).join('')}</div><div class="chart-caption">Contagem diária de aulas não canceladas · 28 set–4 out 2026</div></div></section></div>
    <div class="stack"><section class="panel"><div class="panel-head"><h2>Requer atenção</h2><span class="badge pending">${pending.length} aulas</span></div><div class="plain-list">${pending.slice(0,4).map(a=>`<div class="list-item"><div class="grow"><strong>${esc(a.type)} · ${fmtDate(a.date)}</strong><small>${a.clientIds.filter(id=>(a.paid[id]||0)<(a.charges[id]||0)).map(clientName).map(esc).join(', ')} · pagamento não integral</small></div><button class="text-link" data-detail="class:${a.id}">Ver →</button></div>`).join('')}</div></section><section class="panel"><div class="panel-head"><h2>Relatórios para exportar</h2></div><div class="plain-list">${[['aulas','Aulas','Aulas, situação e participantes'],['pagamentos','Pagamentos','Registros e comprovantes fictícios'],['clientes','Clientes','Cadastro e quantidade de aulas']].map(([id,n,sub])=>`<div class="list-item"><div class="grow"><strong>${n}</strong><small>${sub}</small></div><button class="button small" data-export="${id}">CSV ↓</button></div>`).join('')}</div></section></div></div>`}
  function aulas(){const rows=filteredClasses(),f=state.filters,paidCount=rows.filter(a=>classFinancial(a,f.client)==='paid').length,pendingCount=rows.filter(a=>['pending','partial'].includes(classFinancial(a,f.client))).length;
    return head('Aulas','Planejamento, execução e situação de pagamento por participante.',`<button class="button" data-export="aulas">↓ Exportar recorte</button><button class="button primary" data-new-class>＋ Nova aula</button>`,'AULAS · LIVRO DE AULAS')+
    `<div class="metrics"><div class="panel metric"><span class="label">No recorte</span><div class="number">${rows.length}</div><div class="meta">Aulas encontradas</div></div><div class="panel metric"><span class="label">Planejadas</span><div class="number">${rows.filter(a=>a.status==='planned').length}</div><div class="meta">Ainda não concluídas</div></div><div class="panel metric"><span class="label">Pagas integralmente</span><div class="number">${paidCount}</div><div class="meta">Todas as cobranças cobertas</div></div><div class="panel metric"><span class="label">Pendentes ou parciais</span><div class="number">${pendingCount}</div><div class="meta">Por participante</div></div></div>
    <section class="panel"><div class="toolbar"><input class="input search" aria-label="Buscar aulas" placeholder="Buscar aula, cliente ou instrutor" data-filter="search" value="${esc(f.search||'')}"><select class="select" aria-label="Filtrar cliente" data-filter="client">${options(clients.map(c=>[c.id,c.name]),f.client,'Todos os clientes')}</select><select class="select" aria-label="Filtrar recorrência" data-filter="recurrence">${options([['yes','Recorrentes'],['no','Avulsas']],f.recurrence,'Todas as aulas')}</select><select class="select" aria-label="Filtrar situação" data-filter="status">${options([['planned','Planejadas'],['done','Concluídas'],['cancelled','Canceladas']],f.status,'Toda situação')}</select><select class="select" aria-label="Filtrar pagamento" data-filter="finance">${options([['paid','Pagas'],['due','Pendentes ou parciais'],['partial','Parciais'],['pending','Pendentes'],['trial','Experimentais']],f.finance,'Todo financeiro')}</select><label class="field" style="display:flex;align-items:center;gap:5px">A partir de<input class="input" type="date" data-filter="fromDate" aria-label="Aulas a partir de" value="${esc(f.fromDate||'')}"></label><button class="text-link" data-clear-filters>Limpar</button></div>${table(['Data / hora','Aula','Cliente(s)','Instrutor','Situação','Pagamento',''],rows.map(rowClass).join(''),`${rows.length} aula(s) no recorte · exportação segue os mesmos filtros.`)}</section>`}
  function listPage(title,subtitle,kind,body,headers,foot,actions=''){return head(title,subtitle,actions)+`<section class="panel"><div class="toolbar"><input class="input search" data-list-search="${kind}" aria-label="Buscar ${title.toLowerCase()}" placeholder="Buscar ${title.toLowerCase()}" value="${esc(state.filters[kind+'Search']||'')}"><span class="spacer"></span><span class="subtle">${foot}</span></div>${table(headers,body,foot)}</section>`}
  function clientes(){const q=(state.filters.clientesSearch||'').toLowerCase();const rows=clients.filter(c=>`${c.name} ${c.phone} ${c.email}`.toLowerCase().includes(q));return listPage('Clientes','Cadastros e histórico de aulas e pagamentos por pessoa.','clientes',rows.map(c=>{const a=data.classes.filter(x=>x.clientIds.includes(c.id));return `<tr><td><button class="row-action" data-detail="client:${c.id}">${esc(c.name)}</button><span class="secondary">Cliente desde ${fmtDate(c.since)}</span></td><td>${esc(c.phone)}<span class="secondary">${esc(c.email)}</span></td><td>${badge(c.status,c.status.toLowerCase().includes('inativ')?'':'active')}</td><td>${a.length} aula(s)</td><td>${a.filter(x=>classFinancial(x,c.id)==='paid').length} paga(s)</td><td><button class="text-link" data-detail="client:${c.id}">Abrir ficha →</button></td></tr>`}).join(''),['Cliente','Contato','Situação','Aulas','Pagas',''],`${rows.length} clientes`)}
  function cavalos(){const q=(state.filters.cavalosSearch||'').toLowerCase();const rows=horses.filter(h=>`${h.name} ${h.breed} ${h.owner}`.toLowerCase().includes(q));return listPage('Cavalos','Disponibilidade informada, restrições e uso nas aulas.','cavalos',rows.map(h=>`<tr><td><button class="row-action" data-detail="horse:${h.id}">${esc(h.name)}</button><span class="secondary">${esc(h.breed)}</span></td><td>${esc(h.owner)}</td><td>${esc(h.level)}</td><td>${badge(h.status,h.status==='Em descanso'?'pending':'active')}</td><td>${data.classes.filter(a=>a.horse===h.id).length} aula(s)</td><td><button class="text-link" data-detail="horse:${h.id}">Ver cavalo →</button></td></tr>`).join(''),['Cavalo','Proprietário','Nível','Situação','Uso',''],`${rows.length} cavalos`)}
  function equipe(){const q=(state.filters.equipeSearch||'').toLowerCase();const rows=team.filter(t=>`${t.name} ${t.role}`.toLowerCase().includes(q));return listPage('Equipe','Pessoas, funções e carga dos instrutores. Cadastro profissional não concede acesso ao sistema.','equipe',rows.map(t=>`<tr><td><button class="row-action" data-detail="team:${t.id}">${esc(t.name)}</button><span class="secondary">${esc(t.phone)}</span></td><td>${esc(t.role)}</td><td>${esc(t.capacity)}</td><td>${badge(t.status,'active')}</td><td>${t.role.startsWith('Instrutor')?data.classes.filter(a=>a.instructor===t.id).length+' aulas':'—'}</td><td><button class="text-link" data-detail="team:${t.id}">Abrir ficha →</button></td></tr>`).join(''),['Profissional','Função','Referência diária','Situação','Agenda',''],`${rows.length} profissionais`)}
  function campanhas(){const q=(state.filters.campanhasSearch||'').toLowerCase();const rows=campaigns.filter(c=>`${c.name} ${c.offer}`.toLowerCase().includes(q));return head('Campanhas','Oferta, período, contatos e conversões — com denominador visível.','', 'RELACIONAMENTO')+`<div class="metrics"><div class="panel metric"><span class="label">Campanhas</span><div class="number">${campaigns.length}</div><div class="meta">No catálogo fictício</div></div><div class="panel metric"><span class="label">Contatos</span><div class="number">${campaigns.reduce((s,c)=>s+c.contacts,0)}</div><div class="meta">Pessoas contatadas</div></div><div class="panel metric"><span class="label">Conversões</span><div class="number">${campaigns.reduce((s,c)=>s+c.conversions,0)}</div><div class="meta">Agendamentos / visitas</div></div><div class="panel metric"><span class="label">Taxa total</span><div class="number">${Math.round(campaigns.reduce((s,c)=>s+c.conversions,0)/campaigns.reduce((s,c)=>s+c.contacts,0)*100)}%</div><div class="meta">Conversões ÷ contatos</div></div></div>`+`<section class="panel"><div class="toolbar"><input class="input search" data-list-search="campanhas" aria-label="Buscar campanhas" placeholder="Buscar campanha ou oferta" value="${esc(q)}"><span class="spacer"></span><span class="subtle">${rows.length} campanhas</span></div>${table(['Campanha / oferta','Período','Situação','Contatos','Conversões','Taxa',''],rows.map(c=>`<tr><td><button class="row-action" data-detail="campaign:${c.id}">${esc(c.name)}</button><span class="secondary">${esc(c.offer)}</span></td><td>${fmtDate(c.start)} – ${fmtDate(c.end)}</td><td>${badge(c.status,c.status==='Em andamento'?'active':c.status==='Programada'?'planned':'')}</td><td>${c.contacts}</td><td>${c.conversions}</td><td>${Math.round(c.conversions/c.contacts*100)}%</td><td><button class="text-link" data-detail="campaign:${c.id}">Ver resultados →</button></td></tr>`).join(''),`${rows.length} campanhas · taxa = conversões ÷ contatos; custos não registrados.`)}</section>`}
  function paymentRows(){const f=state.filters;return data.payments.filter(p=>(!f.payClient||p.clientId===f.payClient)&&(!f.paySearch||`${clientName(p.clientId)} ${p.method} ${p.id}`.toLowerCase().includes(f.paySearch.toLowerCase()))).sort((a,b)=>b.date.localeCompare(a.date))}
  function pagamentos(){const rows=paymentRows();return head('Pagamentos','Registros monetários vinculados à aula e ao participante. Experimental não gera pagamento.',`<button class="button" data-export="pagamentos">↓ Exportar recorte</button>`,'FINANCEIRO')+`<div class="metrics"><div class="panel metric"><span class="label">Registros no recorte</span><div class="number">${rows.length}</div><div class="meta">Pagamentos fictícios</div></div><div class="panel metric"><span class="label">Total registrado</span><div class="number">${fmtMoney(rows.reduce((s,p)=>s+p.amount,0))}</div><div class="meta">Soma dos registros filtrados</div></div><div class="panel metric"><span class="label">Aulas vinculadas</span><div class="number">${new Set(rows.map(p=>p.classId)).size}</div><div class="meta">Com pagamento registrado</div></div><div class="panel metric"><span class="label">Com comprovante</span><div class="number">${rows.filter(p=>p.receipt).length}</div><div class="meta">Arquivo apenas ilustrativo</div></div></div><section class="panel"><div class="toolbar"><input class="input search" data-filter="paySearch" aria-label="Buscar pagamentos" placeholder="Buscar cliente ou método" value="${esc(state.filters.paySearch||'')}"><select class="select" data-filter="payClient" aria-label="Filtrar pagamentos por cliente">${options(clients.map(c=>[c.id,c.name]),state.filters.payClient,'Todos os clientes')}</select><button class="text-link" data-clear-pay>Limpar</button></div>${table(['Data','Cliente','Aula vinculada','Método','Valor','Situação',''],rows.map(p=>`<tr><td>${fmtDate(p.date)}</td><td><button class="row-action" data-detail="client:${p.clientId}">${esc(clientName(p.clientId))}</button></td><td><button class="text-link" data-detail="class:${p.classId}">${esc(lookup(data.classes,p.classId)?.type||'Aula')}</button></td><td>${esc(p.method)}</td><td><strong>${fmtMoney(p.amount)}</strong></td><td>${badge(p.status,'paid')}</td><td><button class="text-link" data-detail="payment:${p.id}">Detalhes →</button></td></tr>`).join(''),`${rows.length} pagamento(s) no recorte · exportação segue os mesmos filtros.`)}</section>`}
  function agenda(){const v=state.view,iso=state.date;const period=v==='mes'?fmtDate(iso,{month:'long',year:'numeric'}):v==='semana'?`${fmtDate(weekStart(iso),{day:'numeric',month:'short'})} – ${fmtDate(addDays(weekStart(iso),6),{day:'numeric',month:'short',year:'numeric'})}`:fmtDate(iso,{weekday:'long',day:'numeric',month:'long',year:'numeric'});
    const mobile=matchMedia('(max-width:760px)').matches;if(mobile&&v==='semana'&&!state.manualView){state.view='dia';return agenda()}
    const days=v==='mes'?[]:v==='semana'?Array.from({length:7},(_,i)=>addDays(weekStart(iso),i)):v==='dia'?[iso]:[];
    let calendar='';
    if(v==='semana'||v==='dia'){
      const hourHeight=56,start=7;const header=`<div class="week-head"><div></div>${days.map(d=>`<div class="${d===TODAY?'today':''}">${fmtDate(d,{weekday:'short'}).toUpperCase()}<strong>${Number(d.slice(-2))}</strong></div>`).join('')}</div>`;
      const body=`<div class="week-body ${v==='dia'?'day-view':''}"><div class="hour-labels">${Array.from({length:11},(_,i)=>`<span class="hour-label" style="top:${i*hourHeight}px">${String(i+7).padStart(2,'0')}:00</span>`).join('')}</div>${days.map(d=>`<div class="day-column" data-calendar-day="${d}" aria-label="${fmtDate(d)}; clique em um horário para nova aula">${data.classes.filter(a=>a.date===d&&(!state.filters.calClient||a.clientIds.includes(state.filters.calClient))).map(a=>{const [h,m]=a.time.split(':').map(Number);let top=((h-start)*60+m)/60*hourHeight;return `<button class="cal-event ${a.status}" style="top:${top+2}px;height:${Math.max(37,a.duration/60*hourHeight-4)}px" data-detail="class:${a.id}" title="${esc(a.type)} · ${esc(a.clientIds.map(clientName).join(', '))}"><strong>${a.time} ${esc(a.type)}</strong><small>${esc(a.clientIds.map(clientName).join(', '))}</small></button>`}).join('')}</div>`).join('')}</div>`;
      calendar=`<div class="calendar-shell ${v==='dia'?'day-view':''}">${header}${body}</div>`
    } else if(v==='mes'){
      const first=monthStart(iso),offset=(new Date(first+'T12:00:00').getDay()+6)%7,start=addDays(first,-offset);calendar=`<div class="calendar-shell month-grid">${['Seg','Ter','Qua','Qui','Sex','Sáb','Dom'].map(d=>`<div class="month-label">${d}</div>`).join('')}${Array.from({length:42},(_,i)=>{const d=addDays(start,i),items=data.classes.filter(a=>a.date===d&&(!state.filters.calClient||a.clientIds.includes(state.filters.calClient)));return `<div class="month-cell ${d.slice(0,7)!==iso.slice(0,7)?'muted':''}" data-calendar-day="${d}"><span class="date-num">${Number(d.slice(-2))}</span>${items.slice(0,3).map(a=>`<button class="month-event ${a.status}" data-detail="class:${a.id}">${a.time} ${esc(a.type)}</button>`).join('')}${items.length>3?`<small>+ ${items.length-3}</small>`:''}</div>`}).join('')}</div>`
    } else {
      const from=iso,to=addDays(iso,20),items=data.classes.filter(a=>a.date>=from&&a.date<=to&&(!state.filters.calClient||a.clientIds.includes(state.filters.calClient))).sort(classSort);calendar=`<div class="panel calendar-list">${items.length?Array.from(new Set(items.map(a=>a.date))).map(d=>`<div class="date-group">${fmtDate(d,{weekday:'long',day:'numeric',month:'long'})}</div>${items.filter(a=>a.date===d).map(a=>`<div class="list-item"><span class="time-chip">${a.time}</span><div class="grow"><strong>${esc(a.type)} · ${esc(a.clientIds.map(clientName).join(', '))}</strong><small>${esc(instructorName(a.instructor))} · ${a.duration} min</small></div>${badge(statusLabel[a.status],a.status)}<button class="text-link" data-detail="class:${a.id}">Abrir →</button></div>`).join('')}`).join(''):'<div class="empty">Nenhuma aula nos próximos 21 dias.</div>'}</div>`}
    return head('Agenda','Planejamentos e resultados no tempo. Clique em uma aula para ver participantes e pagamento.',`<button class="button primary" data-new-class>＋ Nova aula</button>`,'AGENDA · VISÃO DE TEMPO')+`<div class="calendar-top"><div class="control-row"><button class="button small" data-cal-prev aria-label="Período anterior">←</button><button class="button small" data-cal-today>Hoje</button><button class="button small" data-cal-next aria-label="Próximo período">→</button><span class="calendar-title">${esc(period)}</span></div><div class="control-row"><select class="select" id="cal-client" aria-label="Filtrar agenda por cliente">${options(clients.map(c=>[c.id,c.name]),state.filters.calClient,'Todos os clientes')}</select><div class="segmented" aria-label="Visualização da agenda">${[['dia','Dia'],['semana','Semana'],['mes','Mês'],['lista','Lista']].map(([id,label])=>`<button data-view="${id}" class="${v===id?'active':''}" aria-pressed="${v===id}">${label}</button>`).join('')}</div></div></div>${calendar}<div class="legend"><span><i></i> Planejada</span><span><i class="ok"></i> Concluída</span><span><i class="red"></i> Cancelada</span><span>Selecione um espaço livre para pré-preencher nova aula.</span></div>`}
  function modal(content,wide=false){const d=$('#detail-dialog');d.classList.toggle('wide',wide);$('#dialog-content').innerHTML=`<div class="dialog-inner">${content}</div>`;d.showModal();$('.dialog-close',d)?.focus()}
  function modalHeader(title,sub=''){return `<div class="dialog-top"><div><p class="eyebrow">ECOBELLA · DADOS FICTÍCIOS</p><h2>${title}</h2>${sub?`<p class="subtle">${sub}</p>`:''}</div><button class="dialog-close" data-close aria-label="Fechar janela">×</button></div>`}
  const datum=(label,value)=>`<div class="datum"><dt>${label}</dt><dd>${value}</dd></div>`;
  function detail(kind,id){const a=kind==='class'?lookup(data.classes,id):null;let body='';
    if(kind==='class'&&a){const fin=classFinancial(a),canFinish=a.status==='planned'&&(fin==='paid'||fin==='trial')&&!!a.horse;body=modalHeader(a.type,`${fmtDate(a.date,{weekday:'long',day:'numeric',month:'long',year:'numeric'})} · ${a.time}–${timeEnd(a)} · ${a.duration} minutos`)+`<div class="detail-heading"><div>${badge(statusLabel[a.status],a.status)} ${badge(statusLabel[fin],fin)} ${a.series?badge('Recorrente','planned'):badge('Avulsa','')}</div></div><div class="detail-section"><h3>Participantes e liberação</h3>${a.clientIds.map(cid=>{let due=a.charges[cid]||0,paid=a.paid[cid]||0,s=a.trial?'trial':paid>=due?'paid':paid?'partial':'pending';return `<div class="participant"><div class="grow"><strong>${esc(clientName(cid))}</strong><span class="secondary">${a.trial?'Gratuita · sem pagamento':`${fmtMoney(paid)} de ${fmtMoney(due)} cobertos`}</span></div>${badge(statusLabel[s],s)}</div>`}).join('')}${fin==='pending'||fin==='partial'?`<p class="note warn">Esta aula segue visível, mas não pode ser concluída enquanto algum participante estiver sem cobertura integral aprovada.</p>`:''}</div><div class="detail-section"><h3>Execução</h3><dl class="info-grid">${datum('Instrutor',esc(instructorName(a.instructor)))}${datum('Cavalo',esc(horseName(a.horse)))}${datum('Origem',a.series?'Série recorrente':'Aula avulsa')}${datum('Presença',a.status==='done'?'Registrada':a.status==='cancelled'?'Não ocorreu':'A registrar na execução')}</dl>${a.reason?`<p class="note crit" style="margin-top:15px">Motivo do cancelamento: ${esc(a.reason)}</p>`:''}</div><div class="dialog-actions">${a.status==='planned'?`<button class="button danger" data-cancel-class="${a.id}">Não concluída</button><button class="button primary" data-complete-class="${a.id}" ${canFinish?'':'disabled'} title="${canFinish?'':'Exige quitação de todos os participantes e cavalo'}">Concluir aula</button>`:''}<button class="button" data-close>Fechar</button></div>`}
    else if(kind==='client'){const c=lookup(clients,id);if(!c)return;let tab=state.tab;let a=data.classes.filter(x=>x.clientIds.includes(id)).sort((x,y)=>classSort(y,x)),p=data.payments.filter(x=>x.clientId===id);const fin=x=>classFinancial(x,id);body=modalHeader(c.name,`${c.status} · cliente desde ${fmtDate(c.since)}`)+`<div class="tabs">${['Dados','Aulas','Pagamentos','Histórico'].map(t=>`<button class="tab ${tab===t?'active':''}" data-client-tab="${t}" data-client-id="${id}">${t}</button>`).join('')}</div>`+(tab==='Dados'?`<dl class="info-grid">${datum('Telefone',esc(c.phone))}${datum('E-mail',esc(c.email))}${datum('Situação',esc(c.status))}${datum('Aulas registradas',String(a.length))}</dl><div class="detail-section section-space"><h3>Observações</h3><p class="subtle">${esc(c.notes)}</p></div>`:tab==='Aulas'?`<p class="subtle">${a.length} aulas · ${a.filter(x=>fin(x)==='paid').length} pagas integralmente · ${a.filter(x=>fin(x)==='trial').length} experimental</p><div class="plain-list section-space">${a.map(x=>`<div class="list-item"><div class="grow"><strong>${fmtDate(x.date)} · ${esc(x.type)}</strong><small>${x.time} · ${statusLabel[x.status]}</small></div>${badge(statusLabel[fin(x)],fin(x))}<button class="text-link" data-detail="class:${x.id}">Abrir →</button></div>`).join('')}</div>`:tab==='Pagamentos'?`<p class="subtle">${p.length} registros · ${fmtMoney(p.reduce((s,x)=>s+x.amount,0))}</p><div class="plain-list section-space">${p.map(x=>`<div class="list-item"><div class="grow"><strong>${fmtDate(x.date)} · ${fmtMoney(x.amount)}</strong><small>${esc(x.method)} · ${esc(lookup(data.classes,x.classId)?.type)}</small></div><button class="text-link" data-detail="payment:${x.id}">Abrir →</button></div>`).join('')||'<div class="empty">Nenhum pagamento registrado.</div>'}</div>`:`<div class="note">Histórico ilustrativo: cadastro em ${fmtDate(c.since)}. Este protótipo não cria trilha de auditoria real.</div>`)+`<div class="dialog-actions"><button class="button" data-close>Fechar ficha</button></div>`}
    else if(kind==='horse'){const h=lookup(horses,id);if(!h)return;const uses=data.classes.filter(a=>a.horse===id).sort((a,b)=>classSort(b,a));body=modalHeader(h.name,`${h.breed} · ${h.status}`)+`<dl class="info-grid">${datum('Proprietário',esc(h.owner))}${datum('Nível',esc(h.level))}${datum('Situação',esc(h.status))}${datum('Aulas vinculadas',String(uses.length))}</dl><div class="detail-section section-space"><h3>Restrições informadas</h3><p class="note warn">${esc(h.restriction)}</p></div><div class="detail-section"><h3>Uso recente e previsto</h3>${uses.slice(0,5).map(a=>`<div class="list-item"><div class="grow"><strong>${fmtDate(a.date)} · ${esc(a.type)}</strong><small>${a.time} · ${esc(instructorName(a.instructor))}</small></div><button class="text-link" data-detail="class:${a.id}">Abrir →</button></div>`).join('')}</div><div class="dialog-actions"><button class="button" data-close>Fechar</button></div>`}
    else if(kind==='team'){const t=lookup(team,id);if(!t)return;const duties=data.classes.filter(a=>a.instructor===id).sort((a,b)=>classSort(a,b));body=modalHeader(t.name,`${t.role} · ${t.status}`)+`<dl class="info-grid">${datum('Telefone',esc(t.phone))}${datum('Referência de carga',esc(t.capacity))}${datum('Função',esc(t.role))}${datum('Aulas vinculadas',t.role.startsWith('Instrutor')?String(duties.length):'Não se aplica')}</dl><div class="detail-section section-space"><h3>Observações</h3><p class="subtle">${esc(t.note)}</p><p class="note section-space">Cadastro da equipe e conta de acesso são vínculos distintos. Nenhum acesso real é provisionado aqui.</p></div>${duties.length?`<div class="detail-section"><h3>Próximas aulas</h3>${duties.filter(a=>a.date>=TODAY).slice(0,4).map(a=>`<div class="list-item"><div class="grow"><strong>${fmtDate(a.date)} · ${a.time}</strong><small>${esc(a.type)}</small></div><button class="text-link" data-detail="class:${a.id}">Abrir →</button></div>`).join('')}</div>`:''}<div class="dialog-actions"><button class="button" data-close>Fechar</button></div>`}
    else if(kind==='campaign'){const c=lookup(campaigns,id);if(!c)return;body=modalHeader(c.name,`${c.offer} · ${fmtDate(c.start)} – ${fmtDate(c.end)}`)+`<div class="metrics" style="grid-template-columns:repeat(3,1fr);margin-top:10px"><div class="panel metric"><span class="label">Contatos</span><div class="number">${c.contacts}</div></div><div class="panel metric"><span class="label">Conversões</span><div class="number">${c.conversions}</div></div><div class="panel metric"><span class="label">Taxa</span><div class="number">${Math.round(c.conversions/c.contacts*100)}%</div></div></div><div class="detail-section"><h3>Oferta e resultado</h3><p class="subtle">${esc(c.description)}</p><p class="note section-space">Denominador: ${c.contacts} contatos alcançados. Numerador: ${c.conversions} agendamentos/visitas confirmados. Custos não informados; ROI não calculado.</p></div><div class="detail-section"><dl class="info-grid">${datum('Situação',badge(c.status,c.status==='Em andamento'?'active':'planned'))}${datum('Período',fmtDate(c.start)+' – '+fmtDate(c.end))}</dl></div><div class="dialog-actions"><button class="button" data-close>Fechar</button></div>`}
    else if(kind==='payment'){const p=lookup(data.payments,id);if(!p)return;body=modalHeader(`Pagamento ${p.id.toUpperCase()}`,`${fmtDate(p.date)} · ${esc(clientName(p.clientId))}`)+`<div class="metrics" style="grid-template-columns:repeat(2,1fr)"><div class="panel metric"><span class="label">Valor registrado</span><div class="number">${fmtMoney(p.amount)}</div></div><div class="panel metric"><span class="label">Situação</span><div style="margin-top:14px">${badge(p.status,'paid')}</div></div></div><div class="detail-section"><dl class="info-grid">${datum('Pagador / participante',`<button class="text-link" data-detail="client:${p.clientId}">${esc(clientName(p.clientId))} →</button>`)}${datum('Aula',`<button class="text-link" data-detail="class:${p.classId}">${esc(lookup(data.classes,p.classId)?.type)} →</button>`)}${datum('Método',esc(p.method))}${datum('Parcelas documentadas',String(p.installments))}${datum('Comprovante ilustrativo',esc(p.receipt))}${datum('Data',fmtDate(p.date))}</dl></div><p class="note">Comprovante é apenas um nome fictício; não há arquivo nem download neste protótipo. Parcelas não criam pagamentos extras.</p><div class="dialog-actions"><button class="button" data-close>Fechar</button></div>`}
    if(body)modal(body,kind==='class'||kind==='client'||kind==='campaign');}
  function timeEnd(a){const [h,m]=a.time.split(':').map(Number),n=h*60+m+a.duration;return `${String(Math.floor(n/60)).padStart(2,'0')}:${String(n%60).padStart(2,'0')}`}
  function newClass(date=state.date,time='09:00'){modal(modalHeader('Nova aula','Planeje uma aula avulsa ou uma série de ocorrências.')+`<form id="new-class-form"><div class="form-grid"><label class="field">Modalidade<select class="select" name="type" required><option value="">Selecione</option><option>Equitação básica</option><option>Salto</option><option>Adestramento</option><option>Experimental</option></select></label><label class="field">Instrutor<select class="select" name="instructor" required><option value="">Selecione</option>${team.filter(t=>t.role.startsWith('Instrutor')).map(t=>`<option value="${t.id}">${esc(t.name)}</option>`).join('')}</select></label><label class="field">Data inicial<input class="input" name="date" type="date" value="${date}" required></label><label class="field">Horário<input class="input" name="time" type="time" value="${time}" required></label><label class="field">Duração<select class="select" name="duration"><option value="45">45 minutos</option><option value="60" selected>60 minutos</option><option value="90">90 minutos</option></select></label><label class="field">Cavalo<select class="select" name="horse" required><option value="">Selecione</option>${horses.filter(h=>h.status!=='Em descanso').map(h=>`<option value="${h.id}">${esc(h.name)}</option>`).join('')}</select></label></div><div class="form-divider">PARTICIPANTES</div><div class="check-list">${clients.filter(c=>c.status!=='Inativo').map(c=>`<label class="check-line"><input type="checkbox" name="clients" value="${c.id}"> ${esc(c.name)}</label>`).join('')}</div><div class="form-divider">REPETIÇÃO</div><div class="form-grid"><label class="field">Frequência<select class="select" name="repeat"><option value="none">Não se repete</option><option value="weekly">Semanal</option><option value="custom">Personalizada</option></select></label><label class="field repeat-only" hidden>Até quando<input class="input" type="date" name="until" value="${addDays(date,28)}"></label><label class="field repeat-custom" hidden>Intervalo<select class="select" name="interval"><option value="2">A cada 2 semanas</option><option value="3">A cada 3 semanas</option><option value="4">A cada 4 semanas</option></select></label></div><div class="preview" id="date-preview">Uma ocorrência em ${fmtDate(date)}.</div><p class="subtle" style="margin-top:11px">Dono · simulação local. Preços fictícios por tipo são copiados por participante; uma série não registra conclusão nem cobrança como paga.</p><div class="dialog-actions"><button class="button" type="button" data-close>Cancelar</button><button class="button primary" type="submit">Planejar aula</button></div></form>`,true);updatePreview()}
  function recurrenceDates(form){const date=form.elements.date.value,until=form.elements.until.value,repeat=form.elements.repeat.value,interval=repeat==='custom'?Number(form.elements.interval.value):1;if(!date)return [];if(repeat==='none')return [date];if(!until||until<date)return [];const dates=[];let next=date;while(next<=until&&dates.length<52){dates.push(next);next=addDays(next,7*interval)}return dates}
  function updatePreview(){const f=$('#new-class-form');if(!f)return;const repeat=f.elements.repeat.value;$('.repeat-only',f).hidden=repeat==='none';$('.repeat-custom',f).hidden=repeat!=='custom';const dates=recurrenceDates(f);$('#date-preview').textContent=dates.length?`${dates.length} ocorrência(s): ${dates.slice(0,6).map(d=>fmtDate(d,{day:'numeric',month:'short'})).join(' · ')}${dates.length>6?' · …':''}${dates.length===52?' · limite de 52 ocorrências':''}`:'Defina um término igual ou posterior à data inicial.'}
  function createClass(f){const dates=recurrenceDates(f),ids=[...f.querySelectorAll('[name="clients"]:checked')].map(el=>el.value),type=f.elements.type.value;if(!dates.length){notify('Informe uma data de término válida.');return}if(!ids.length){notify('Selecione pelo menos um participante.');return}if(type==='Experimental'&&ids.length!==1){notify('A aula experimental requer um participante.');return}if(type==='Experimental'&&dates.length>1){notify('Experimental gratuita não pode se repetir. Selecione “Não se repete”.');return}if(type==='Experimental'&&ids.some(id=>data.classes.some(a=>a.trial&&a.clientIds.includes(id)&&a.status!=='cancelled'))){notify('Já existe experimental deste tipo para este cliente nos dados fictícios.');return}const rates={'Equitação básica':180,'Salto':220,'Adestramento':200,'Experimental':0};const series=dates.length>1?'v2-'+Date.now():null;for(const d of dates){const id='v2-'+crypto.randomUUID();data.classes.push({id,date:d,time:f.elements.time.value,duration:Number(f.elements.duration.value),type,instructor:f.elements.instructor.value,clientIds:ids,horse:f.elements.horse.value,status:'planned',series,trial:type==='Experimental',charges:Object.fromEntries(ids.map(cid=>[cid,rates[type]])),paid:Object.fromEntries(ids.map(cid=>[cid,0]))})}save();$('#detail-dialog').close();notify(`${dates.length} aula(s) planejada(s) nos dados fictícios.`);state.date=dates[0];state.filters={};route('aulas')}
  function completeClassForm(a){modal(modalHeader('Concluir aula',`${esc(a.type)} · ${fmtDate(a.date)} às ${a.time}`)+`<form id="complete-class-form" data-class-id="${a.id}"><p class="note">Confirme a presença e o cavalo usados nesta simulação. A liberação financeira é verificada para cada participante.</p><div class="form-divider">PRESENÇA</div><div class="check-list">${a.clientIds.map(cid=>`<label class="check-line"><input type="checkbox" name="attendance" value="${cid}"> ${esc(clientName(cid))}</label>`).join('')}</div><div class="form-divider">CAVALO E OBSERVAÇÕES</div><div class="form-grid"><label class="field">Cavalo utilizado<select class="select" name="horse" required><option value="">Selecione</option>${horses.map(h=>`<option value="${h.id}" ${a.horse===h.id?'selected':''}>${esc(h.name)}</option>`).join('')}</select></label><label class="field full">Observações<textarea name="notes" rows="3" maxlength="300" placeholder="Opcional"></textarea></label></div><div class="dialog-actions"><button class="button" type="button" data-detail="class:${a.id}">Voltar</button><button class="button primary" type="submit">Confirmar conclusão fictícia</button></div></form>`,true)}
  function cancelClassForm(a){modal(modalHeader('Aula não concluída',`${esc(a.type)} · ${fmtDate(a.date)} às ${a.time}`)+`<form id="cancel-class-form" data-class-id="${a.id}"><p class="note warn">O cancelamento não estorna pagamentos nem cria créditos automaticamente. Tratamento financeiro é uma decisão manual.</p><div class="form-grid section-space"><label class="field full">Motivo<select class="select" name="reason" required><option value="">Selecione</option>${['Chuva','Outro fator climático','Ausência do aluno','Ausência do instrutor','Cavalo indisponível','Estrutura','Outro'].map(x=>`<option>${x}</option>`).join('')}</select></label><label class="field full">Detalhes<textarea name="reasonDetail" rows="3" maxlength="300" placeholder="Obrigatório para Outro"></textarea></label></div><div class="dialog-actions"><button type="button" class="button" data-detail="class:${a.id}">Voltar</button><button type="submit" class="button danger">Confirmar não conclusão fictícia</button></div></form>`,true)}
  function exportData(kind){if(kind==='aulas'){const rows=filteredClasses();csv('ecobella-v2-aulas-ficticias.csv',['Data','Horário','Modalidade','Clientes','Instrutor','Situação','Financeiro','Recorrente'],rows.map(a=>[a.date,a.time,a.type,a.clientIds.map(clientName).join(' / '),instructorName(a.instructor),statusLabel[a.status],statusLabel[classFinancial(a,state.filters.client)],a.series?'Sim':'Não']))}else if(kind==='pagamentos'){const rows=paymentRows();csv('ecobella-v2-pagamentos-ficticios.csv',['Data','Cliente','Aula','Valor BRL','Método','Comprovante fictício'],rows.map(p=>[p.date,clientName(p.clientId),lookup(data.classes,p.classId)?.type,p.amount.toFixed(2),p.method,p.receipt]))}else{csv('ecobella-v2-clientes-ficticios.csv',['Cliente','Situação','Aulas','Aulas pagas'],clients.map(c=>{const a=data.classes.filter(x=>x.clientIds.includes(c.id));return[c.name,c.status,a.length,a.filter(x=>classFinancial(x,c.id)==='paid').length]}))}}
  function bindPage(){/* Event delegation is registered once below. */}
  document.addEventListener('click',e=>{const target=e.target.closest('button,[data-go],[data-calendar-day]');if(!target)return;
    if(target.matches('[data-close]')){$('#detail-dialog').close();return}
    if(target.dataset.detail){const [kind,id]=target.dataset.detail.split(':');detail(kind,id);return}
    if(target.dataset.go){if(target.dataset.finance||target.hasAttribute('data-upcoming'))state.filters={status:'planned',fromDate:TODAY,...(target.dataset.finance?{finance:target.dataset.finance}:{})};route(target.dataset.go);return}
    if(target.hasAttribute('data-new-class')){newClass();return}
    if(target.dataset.export){exportData(target.dataset.export);return}
    if(target.dataset.view){state.view=target.dataset.view;state.manualView=true;render();return}
    if(target.hasAttribute('data-cal-prev')||target.hasAttribute('data-cal-next')){let n=target.hasAttribute('data-cal-prev')?-1:1;state.date=state.view==='mes'?monthShift(state.date,n):addDays(state.date,n*(state.view==='semana'?7:state.view==='lista'?21:1));render();return}
    if(target.hasAttribute('data-cal-today')){state.date=TODAY;render();return}
    if(target.dataset.calendarDay){const rect=target.getBoundingClientRect();let time='09:00';if(target.classList.contains('day-column')){let minute=Math.max(0,Math.min(10*60,Math.floor((e.clientY-rect.top)/56*60/30)*30));time=`${String(Math.floor((minute+420)/60)).padStart(2,'0')}:${String((minute+420)%60).padStart(2,'0')}`}newClass(target.dataset.calendarDay,time);return}
    if(target.hasAttribute('data-clear-filters')){state.filters={};render();return}
    if(target.hasAttribute('data-clear-pay')){delete state.filters.payClient;delete state.filters.paySearch;render();return}
    if(target.dataset.clientTab){state.tab=target.dataset.clientTab;detail('client',target.dataset.clientId);return}
    if(target.dataset.completeClass){const a=lookup(data.classes,target.dataset.completeClass);if(classFinancial(a)!=='paid'&&classFinancial(a)!=='trial'){notify('Conclusão bloqueada: pagamento pendente.');return}completeClassForm(a);return}
    if(target.dataset.cancelClass){cancelClassForm(lookup(data.classes,target.dataset.cancelClass));return}
  });
  document.addEventListener('input',e=>{const t=e.target;if(t.closest('#new-class-form')){if(['date','until','repeat','interval'].includes(t.name))updatePreview();return}if(t.dataset.filter){state.filters[t.dataset.filter]=t.value;const pos=t.selectionStart;render();if(t.tagName==='INPUT'){const replacement=$(`[data-filter="${t.dataset.filter}"]`);replacement?.focus();replacement?.setSelectionRange(pos,pos)}return}if(t.dataset.listSearch){state.filters[t.dataset.listSearch+'Search']=t.value;const pos=t.selectionStart;render();const replacement=$(`[data-list-search="${t.dataset.listSearch}"]`);replacement?.focus();replacement?.setSelectionRange(pos,pos)}if(t.id==='cal-client'){state.filters.calClient=t.value;render()}});
  document.addEventListener('change',e=>{if(e.target.closest('#new-class-form'))updatePreview()});
  document.addEventListener('submit',e=>{if(e.target.id==='new-class-form'){e.preventDefault();createClass(e.target)}if(e.target.id==='complete-class-form'){e.preventDefault();const f=e.target,a=lookup(data.classes,f.dataset.classId),present=[...f.querySelectorAll('[name="attendance"]:checked')].map(x=>x.value);if(!present.length){notify('Marque pelo menos um participante presente.');return}if(!a||a.status!=='planned'||!['paid','trial'].includes(classFinancial(a))){notify('Aula não está liberada para conclusão.');return}a.status='done';a.horse=f.elements.horse.value;a.attendance=present;a.notes=f.elements.notes.value;save();$('#detail-dialog').close();notify('Conclusão e presença simuladas nos dados fictícios.');render()}if(e.target.id==='cancel-class-form'){e.preventDefault();const f=e.target,a=lookup(data.classes,f.dataset.classId),reason=f.elements.reason.value,extra=f.elements.reasonDetail.value.trim();if(reason==='Outro'&&!extra){notify('Descreva o motivo “Outro”.');return}if(!a||a.status!=='planned'){notify('Somente uma aula planejada pode ser marcada como não concluída.');return}a.reason=reason+(extra?' · '+extra:'');a.status='cancelled';save();$('#detail-dialog').close();notify('Não conclusão simulada. Nenhum estorno automático.');render()}});
  $('#detail-dialog').addEventListener('click',e=>{if(e.target.id==='detail-dialog')e.target.close()});
  $('#menu-toggle').addEventListener('click',()=>{const s=$('#sidebar');const open=s.classList.toggle('open');$('#menu-toggle').setAttribute('aria-expanded',String(open))});
  $('#help').addEventListener('click',()=>modal(modalHeader('Sobre este protótipo','Ecobella v2 · dados fictícios')+`<p class="subtle">Interface independente em HTML, CSS e JavaScript. Os registros inventados ficam somente no navegador deste dispositivo. Nenhum acesso a Supabase ou a pessoas reais.</p><div class="detail-section section-space"><h3>Restaurar demonstração</h3><p class="subtle">Apaga apenas as edições simuladas guardadas sob a chave local exclusiva deste protótipo.</p></div><div class="dialog-actions"><button class="button danger" id="reset-demo">Restaurar dados fictícios</button><button class="button" data-close>Fechar</button></div>`));
  document.addEventListener('click',e=>{if(e.target.id==='reset-demo'){data=structuredClone(seed);localStorage.removeItem(KEY);state.filters={};$('#detail-dialog').close();notify('Dados fictícios restaurados.');render()}});
  window.addEventListener('hashchange',render);
  window.addEventListener('keydown',e=>{if(e.key==='Escape'&&$('#sidebar').classList.contains('open')){$('#sidebar').classList.remove('open');$('#menu-toggle').setAttribute('aria-expanded','false')}});
  render();
})();
