/* Fictional class results. Commands share the financial lock and keep historical records. */
(() => {
  'use strict';
  const attendance={present:'Presente',absent:'Ausente',justified_absence:'Ausência justificada'};
  const modes=['complete','cancel','correct','void'];
  const reasons=['Chuva','Outro fator climático','Ausência do aluno','Ausência do instrutor','Cavalo indisponível','Estrutura','Outro'];
  function install(c){
    const {$,esc,modal,modalHeader,closeModal,render,notify,refresh,save,audit}=c;
    const row=id=>c.getClasses().find(a=>a.id===id);
    const identity=a=>JSON.stringify({status:a.status,voidedAt:a.voidedAt||null,date:a.date,time:a.time,duration:a.duration,instructor:a.instructor,type:a.type,horse:a.horse,clientIds:a.clientIds,charges:a.charges,trial:!!a.trial,result:a.result||null});
    const can=(mode,a)=>modes.includes(mode)&&!!a&&c.active()&&c.own(a)&&(mode==='complete'?c.finishAllowed(a):mode==='cancel'?c.cancelAllowed(a):c.edit());
    const planned=a=>a.status==='planned'&&!a.voidedAt;
    const released=a=>a.clientIds.length>0&&['paid','trial'].includes(c.financialState(a));
    const recorded=a=>a.status==='done'&&!a.voidedAt;
    const horseActive=h=>!!h&&h.active!==false&&!/inativ/i.test(h.status||'');
    function attendanceFields(a,values=[]){return a.clientIds.map(id=>`<label class="field">Presença de ${esc(c.clientName(id))}<select class="select" name="attendance-${esc(id)}" aria-label="Presença de ${esc(c.clientName(id))}" aria-describedby="class-command-error"><option value="">Informe a presença</option>${Object.entries(attendance).map(([value,label])=>`<option value="${value}" ${values.find(x=>x.clientId===id)?.attendance===value?'selected':''}>${label}</option>`).join('')}</select></label>`).join('')}
    function horseFields(a,n,horseId=''){return `<fieldset class="class-horse" data-horse-row><legend>Cavalo ${n}</legend><div class="form-grid"><label class="field">Cavalo utilizado ${n}<select class="select" name="horseId" aria-label="Cavalo utilizado ${n}" aria-describedby="horse-warning class-command-error"><option value="">Selecione</option>${c.getData().horses.filter(horseActive).map(h=>`<option value="${esc(h.id)}" ${h.id===horseId?'selected':''}>${esc(h.name)}</option>`).join('')}</select></label><label class="field">Participante montado ${n}<select class="select" name="rider" aria-label="Participante montado ${n}"><option value="">Apoio, sem cavaleiro</option>${a.clientIds.map(id=>`<option value="${esc(id)}">${esc(c.clientName(id))}</option>`).join('')}</select></label><label class="field">Minutos utilizados ${n}<input class="input" type="number" name="minutes" min="1" max="600" step="1" aria-label="Minutos utilizados ${n}" aria-describedby="class-command-error" placeholder="Não informado"></label><label class="field">Observações do cavalo ${n}<textarea class="input" name="horseNotes" maxlength="1000" aria-label="Observações do cavalo ${n}"></textarea></label></div>${n>1?'<button class="button small" type="button" data-remove-horse>Remover cavalo</button>':''}</fieldset>`}
    function warning(){const f=$('#complete-class-form');if(!f)return;const messages=[...f.querySelectorAll('[name=horseId]')].map(el=>c.getData().horses.find(h=>h.id===el.value)).filter(Boolean).map(h=>`${h.name}: ${h.status}. ${h.restriction||'Sem restrição informada.'}`);$('#horse-warning').textContent=messages.join(' · ')}
    function form(mode,id){refresh();const a=row(id);if(!can(mode,a))return;if((mode==='complete'||mode==='cancel')&&!planned(a))return;if(mode==='complete'&&!released(a)){notify('Conclusão bloqueada: aula não liberada.');return}if(['correct','void'].includes(mode)&&!recorded(a))return;if(mode==='correct'&&!a.result){notify('Resultado histórico não informado; não é possível presumir participantes e uso efetivos.');return}
      const title={complete:'Concluir aula',cancel:'Aula não concluída',correct:'Corrigir resultado',void:'Anular resultado'}[mode],submit={complete:'Confirmar conclusão fictícia',cancel:'Confirmar não conclusão fictícia',correct:'Salvar correção',void:'Confirmar anulação'}[mode];
      const content=mode==='complete'?`<p class="note">Informe presença de todos os participantes e pelo menos um cavalo. Descanso e restrições são avisos; confira com a equipe.</p><div class="form-grid">${attendanceFields(a)}</div><div id="class-horses">${horseFields(a,1,a.horse)}</div><button class="button small" type="button" data-add-horse>Adicionar cavalo</button><p id="horse-warning" class="note warn" role="status"></p><label class="field">Observações<textarea class="input" name="notes" maxlength="300" aria-label="Observações"></textarea></label>`:mode==='correct'?`<p class="note">Corrige somente a presença. Participantes, cavalos, minutos, observações e situação permanecem como registrados.</p><div class="form-grid">${attendanceFields(a,a.result.participants)}</div>`:mode==='cancel'?`<p class="note warn">Não estorna pagamentos, não cria créditos nem reposição. Reserva experimental anterior à conclusão será liberada.</p><label class="field">Motivo<select class="select" name="reason" aria-label="Motivo"><option value="">Selecione</option>${reasons.map(x=>`<option>${x}</option>`).join('')}</select></label><label class="field">Detalhes<textarea class="input" name="reasonDetail" maxlength="300" aria-label="Detalhes"></textarea></label>`:`<p class="note warn">Anular retira esta aula dos totais operacionais. O resultado, os pagamentos e o consumo experimental permanecem no histórico. Conferência financeira manual; nenhuma reposição ou crédito automático.</p><label class="field">Motivo da anulação<textarea class="input" name="reason" maxlength="500" aria-label="Motivo da anulação"></textarea></label>`;
      modal(modalHeader(title,`${esc(a.type)} · ${c.fmtDate(a.date)} às ${esc(a.time)}`)+`<form id="${mode==='complete'?'complete':mode==='cancel'?'cancel':mode==='correct'?'correct':'void'}-class-form" data-class-command="${mode}" data-class-id="${esc(id)}" data-request-id="${crypto.randomUUID()}" novalidate>${content}<p id="class-command-error" role="alert" tabindex="-1"></p><div class="dialog-actions"><button type="button" class="button" data-close>Voltar</button><button type="submit" class="button ${mode==='void'||mode==='cancel'?'danger':'primary'}">${submit}</button></div></form>`,true);
      const f=$('[data-class-command]');f.classMode=mode;f.horseSequence=1;f.classActor=c.actor();f.classBefore=identity(a);f.querySelector('select,textarea')?.focus();warning();
    }
    function values(f,a,mode){if(['complete','correct'].includes(mode)){const participants=a.clientIds.map(clientId=>({clientId,attendance:f.elements['attendance-'+clientId]?.value}));if(!participants.length||participants.some(x=>!Object.hasOwn(attendance,x.attendance)))throw Error('Informe presença válida de todos os participantes.');if(mode==='correct')return{participants};const horses=[...f.querySelectorAll('[data-horse-row]')].map(el=>{const horseId=$('[name=horseId]',el).value,participantClientId=$('[name=rider]',el).value||null,raw=$('[name=minutes]',el).value,usedMinutes=raw===''?null:Number(raw),notes=$('[name=horseNotes]',el).value.trim();if(!horseActive(c.getData().horses.find(h=>h.id===horseId)))throw Error('Escolha cavalo existente e ativo.');if(participantClientId&&!a.clientIds.includes(participantClientId))throw Error('Participante montado deve pertencer à aula.');if(usedMinutes!==null&&(!Number.isInteger(usedMinutes)||usedMinutes<1||usedMinutes>600))throw Error('Minutos utilizados: informe inteiro de 1 a 600, ou deixe não informado.');if(notes.length>1000)throw Error('Observações do cavalo: até 1000 caracteres.');return{horseId,participantClientId,usedMinutes,notes}});if(!horses.length)throw Error('Informe pelo menos um cavalo.');if(new Set(horses.map(x=>JSON.stringify([x.horseId,x.participantClientId]))).size!==horses.length)throw Error('Não repita o par cavalo e participante, incluindo apoio.');if(horses.some(h=>horses.filter(x=>x.horseId===h.horseId).length>1&&h.usedMinutes===null))throw Error('Informe minutos de cada uso do cavalo compartilhado.');const notes=f.elements.notes.value.trim();if(notes.length>300)throw Error('Observações: até 300 caracteres.');return{participants,horses,notes}}
      const reason=f.elements.reason.value.trim();if(mode==='void'){if(!reason||reason.length>500)throw Error('Informe motivo da anulação, até 500 caracteres.');return{reason}}const detail=f.elements.reasonDetail.value.trim();if(!reasons.includes(reason))throw Error('Escolha motivo válido.');if(reason==='Outro'&&!detail)throw Error('Informe detalhe para o motivo Outro.');if(detail.length>300)throw Error('Detalhes: até 300 caracteres.');return{reason,detail};
    }
    function finish(f,mode){f.dataset.pending='false';c.markParents();closeModal();if(['complete','cancel'].includes(mode))closeModal();else c.replaceDetail('class',f.dataset.classId);render();notify('Resultado fictício salvo. Pagamentos preservados.');}
    async function submit(f){if(f.dataset.pending==='true')return;const error=message=>{if(f.isConnected){$('#class-command-error').textContent=message;$('#class-command-error').focus()}},mode=f.dataset.classCommand;if(!modes.includes(mode)||mode!==f.classMode)return error('Comando inválido. Nenhuma alteração registrada.');if(!navigator.locks)return error('Navegador sem bloqueio local seguro.');f.dataset.pending='true';const controls=[...f.querySelectorAll('input,select,textarea,button')].map(el=>[el,el.disabled]);controls.forEach(([el])=>el.disabled=true);
      try{await navigator.locks.request(c.key,()=>{refresh();if(mode!==f.classMode||mode!==f.dataset.classCommand)throw Error('Comando inválido. Nenhuma alteração registrada.');const a=row(f.dataset.classId);if(c.actor()!==f.classActor||!can(mode,a))throw Error('Sem permissão para alterar esta aula.');const input=values(f,a,mode),canonical=JSON.stringify({author:f.classActor,mode,classId:a.id,...input}),data=c.getData(),commands=data.classCommands||[],prior=commands.find(x=>x.requestId===f.dataset.requestId);if(prior){if(prior.canonical!==canonical)throw Error('Esta operação já foi registrada com outros dados. Confira o histórico.');finish(f,mode);return}if(identity(a)!==f.classBefore)throw Error('A aula mudou em outra aba. Reabra o resultado antes de confirmar.');if(['complete','cancel'].includes(mode)&&!planned(a))throw Error('Somente aula planejada pode receber este comando.');if(mode==='complete'&&!released(a))throw Error('Aula não está liberada: confira cobertura de todos os participantes.');if(['correct','void'].includes(mode)&&!recorded(a))throw Error('Resultado não está disponível para alteração.');if(mode==='correct'&&!a.result)throw Error('Resultado histórico não informado.');const snapshot=c.snapshot(),before=structuredClone(a),now=new Date().toISOString();
        try{if(mode==='complete'){a.status='done';a.result={...input,author:c.actorName(),recordedAt:now};a.attendance=input.participants.filter(x=>x.attendance==='present').map(x=>x.clientId);a.horse=input.horses[0].horseId;a.notes=input.notes;if(a.trial)a.trialConsumed=true}else if(mode==='correct'){a.result.participants=a.result.participants.map(x=>({...x,attendance:input.participants.find(p=>p.clientId===x.clientId).attendance}));a.attendance=a.result.participants.filter(x=>x.attendance==='present').map(x=>x.clientId);a.correctedAt=now;a.correctedBy=c.actorName()}else if(mode==='cancel'){a.status='cancelled';a.reason=input.reason+(input.detail?' · '+input.detail:'');a.cancelReason=input.reason;a.cancelDetails=input.detail;a.cancelledAt=now;a.cancelledBy=c.actorName()}else{a.voidedAt=now;a.voidReason=input.reason;a.voidedBy=c.actorName();if(a.trial)a.trialConsumed=true}
          data.classCommands=[...commands,{requestId:f.dataset.requestId,canonical}];audit('class',a.id,before,a,{complete:'Concluir aula',correct:'Corrigir resultado',cancel:'Cancelar aula',void:'Anular resultado'}[mode]);save();
        }catch{c.restore(snapshot);throw Error('Não foi possível salvar os dados locais. Campos e operação preservados; tente novamente.')}finish(f,mode);
      })}catch(e){error(e.message)}finally{f.dataset.pending='false';controls.forEach(([el,disabled])=>el.disabled=disabled)}
    }
    function result(a){if(a.status!=='done')return'';const r=a.result,legacy=!r;return `<section id="class-result" class="detail-section"><h3>Resultado salvo ${a.voidedAt?'· Anulada':''}</h3>${a.voidedAt?`<p class="note crit">Anulada · ${esc(a.voidedBy||'Autor não informado')} · ${esc(a.voidedAt)} · ${esc(a.voidReason)}. Pagamentos e consumo experimental conservados.</p>`:''}${legacy?'<p class="note">Não informado: resultado individual, minutos efetivos, autor e data não constam no registro anterior. O cavalo acima é referência do planejamento.</p>':`<p class="subtle">${esc(r.author)} · ${esc(r.recordedAt)}</p>${r.participants.map(p=>`<p><strong>${esc(c.clientName(p.clientId))}</strong>: ${esc(attendance[p.attendance]||'Não informado')}${p.notes?' · '+esc(p.notes):''}</p>`).join('')}<h4>Cavalos utilizados</h4>${r.horses.map(h=>`<p><strong>${esc(c.horseName(h.horseId))}</strong> · ${h.usedMinutes==null?'Minutos não informados':h.usedMinutes+' min'} · ${h.participantClientId?esc(c.clientName(h.participantClientId)):'Apoio, sem cavaleiro'}${h.notes?' · '+esc(h.notes):''}</p>`).join('')}<p>Observações: ${esc(r.notes||'Não informadas')}</p>`}${c.edit()&&!a.voidedAt?`<div class="dialog-actions">${r?`<button class="button" data-correct-class="${esc(a.id)}">Corrigir resultado</button>`:''}<button class="button danger" data-void-class="${esc(a.id)}">Anular resultado</button></div>`:''}</section>`}
    function history(a){if(c.instructor())return'<p class="note">Histórico administrativo restrito a Dono, Administrativo e Gerente.</p>';const events=c.getData().history.filter(x=>x.kind==='class'&&x.recordId===a.id);const projection=value=>value?{situação:value.status,participantes:value.clientIds?.map(c.clientName),presenças:value.result?.participants?.map(x=>({cliente:c.clientName(x.clientId),presença:attendance[x.attendance]||'Não informado'})),cavalos:value.result?.horses?.map(x=>({cavalo:c.horseName(x.horseId),minutos:x.usedMinutes,participante:x.participantClientId?c.clientName(x.participantClientId):null,observações:x.notes})),observações:value.result?.notes,motivo:value.reason||value.voidReason,anuladaEm:value.voidedAt}:null;return `<section id="class-history" class="detail-section"><h3>Histórico da aula</h3>${events.map(x=>`<details><summary>${esc(x.action)} · ${esc(x.author)} · ${esc(x.date)}</summary><p>Antes</p><pre class="class-audit">${esc(JSON.stringify(projection(x.before),null,2))}</pre><p>Depois</p><pre class="class-audit">${esc(JSON.stringify(projection(x.after),null,2))}</pre></details>`).join('')||'<p>Histórico anterior não informado.</p>'}</section>`}
    function links(a){return `<section class="detail-section"><h3>Registros relacionados</h3>${!c.instructor()?a.clientIds.map(id=>`<button class="text-link" data-detail="client:${esc(id)}">Abrir cliente ${esc(c.clientName(id))}</button>`).join(' · '):''}${c.financial()?c.getData().payments.filter(p=>p.classId===a.id||(p.allocations||[]).some(x=>x.classId===a.id)).map(p=>`<p><button class="text-link" data-detail="payment:${esc(p.id)}">Abrir pagamento ${esc(p.id)}</button>${p.voidedAt?' · Estornado':''}</p>`).join(''):''}</section>`}
    document.addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;for(const [attribute,mode]of[['completeClass','complete'],['cancelClass','cancel'],['correctClass','correct'],['voidClass','void']])if(b.dataset[attribute]){form(mode,b.dataset[attribute]);return}const f=b.closest('#complete-class-form');if(f?.dataset.pending==='true')return;if(b.hasAttribute('data-add-horse')&&f){const a=row(f.dataset.classId),n=++f.horseSequence;$('#class-horses').insertAdjacentHTML('beforeend',horseFields(a,n));$('#class-horses [data-horse-row]:last-child select').focus()}if(b.hasAttribute('data-remove-horse')&&f){b.closest('[data-horse-row]').remove();f.querySelector('[data-add-horse]').focus();warning()}});
    document.addEventListener('change',e=>{if(e.target.name==='horseId')warning()});
    document.addEventListener('input',e=>{if(e.target.closest('[data-class-command]'))$('#class-command-error').textContent=''});
    document.addEventListener('submit',e=>{if(e.target.matches('[data-class-command]')){e.preventDefault();submit(e.target)}});
    return{result,history,links};
  }
  globalThis.EcobellaClasses={install};
})();
