/* Financial simulation: integer cents, local attachments, no remote requests. */
(() => {
  'use strict';
  const MAX_BYTES = 20 * 1024 * 1024;
  const methods = ['Pix','Dinheiro','Boleto','Cartão de débito','Cartão de crédito','Cartão'];
  const types = {pdf:'application/pdf',png:'image/png',jpg:'image/jpeg',jpeg:'image/jpeg',webp:'image/webp',gif:'image/gif',txt:'text/plain',csv:'text/csv',doc:'application/msword',docx:'application/vnd.openxmlformats-officedocument.wordprocessingml.document',odt:'application/vnd.oasis.opendocument.text',rtf:'application/rtf',xls:'application/vnd.ms-excel',xlsx:'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'};
  function cents(value) {
    const text=String(value??'').trim().replace(',','.');
    if(!/^\d{1,10}(\.\d{1,2})?$/.test(text))return null;
    const [whole,fraction='']=text.split('.');
    return Number(whole)*100+Number(fraction.padEnd(2,'0'));
  }
  function allocations(p){return p.allocations||[{classId:p.classId,clientId:p.clientId,amountCents:cents(p.amount)}]}
  function validPayment(p,classes) {
    return !p.legacy&&!p.voidedAt&&p.receiptConfirmed&&p.attachment?.size>0&&p.attachment.size<=MAX_BYTES&&Number.isSafeInteger(p.amountCents)&&p.amountCents>0&&
      allocations(p).every(a=>Number.isSafeInteger(a.amountCents)&&a.amountCents>0&&classes.some(c=>c.id===a.classId&&!c.trial&&c.clientIds.includes(a.clientId)))&&
      allocations(p).reduce((sum,a)=>sum+a.amountCents,0)<=p.amountCents;
  }
  function initialize(data,classes) {
    if(!data.legacyCoverage){
      data.legacyCoverage=Object.fromEntries(classes.map(a=>[a.id,Object.fromEntries(a.clientIds.map(id=>[id,cents(a.paid?.[id]||0)||0]))]));
      for(const p of data.payments)if(!p.amountCents)p.legacy=true;
    }
  }
  function addMonths(date,offset){const d=new Date(date+'T12:00:00Z'),day=d.getUTCDate();d.setUTCDate(1);d.setUTCMonth(d.getUTCMonth()+offset);const end=new Date(Date.UTC(d.getUTCFullYear(),d.getUTCMonth()+1,0)).getUTCDate();d.setUTCDate(Math.min(day,end));return d.toISOString().slice(0,10)}
  function coverage(data,classes,a,id){
    initialize(data,classes);
    const removed=data.payments.filter(p=>p.legacy&&p.voidedAt).flatMap(p=>p.legacyRefundLinks||[]).filter(x=>x.classId===a.id&&x.clientId===id).reduce((sum,x)=>sum+x.amountCents,0);
    return Math.max(0,(data.legacyCoverage[a.id]?.[id]||0)-removed)+data.payments.filter(p=>validPayment(p,classes)).reduce((sum,p)=>sum+allocations(p).filter(x=>x.classId===a.id&&x.clientId===id).reduce((s,x)=>s+x.amountCents,0),0);
  }
  function sync(data,classes){initialize(data,classes);for(const a of classes)a.paid=Object.fromEntries(a.clientIds.map(id=>[id,coverage(data,classes,a,id)/100]))}
  async function validateFile(file) {
    if(!file||!file.size)throw Error('Anexe um comprovante com conteúdo.');
    if(file.size>MAX_BYTES)throw Error('Arquivo excede 20 MiB.');
    const ext=file.name.toLowerCase().split('.').at(-1),mime=types[ext];
    if(!mime||file.type&&file.type!==mime&&!(ext==='rtf'&&file.type==='text/rtf'))throw Error('Formato inválido. Use PDF, imagem ou documento permitido.');
    const bytes=new Uint8Array(await file.slice(0,16).arrayBuffer()),head=String.fromCharCode(...bytes);
    const correct=ext==='pdf'?head.startsWith('%PDF-'):ext==='png'?bytes[0]===137&&head.slice(1,4)==='PNG':/jpe?g/.test(ext)?bytes[0]===255&&bytes[1]===216&&bytes[2]===255:ext==='gif'?/^GIF8[79]a/.test(head):ext==='webp'?head.startsWith('RIFF')&&head.slice(8,12)==='WEBP':['docx','xlsx','odt'].includes(ext)?head.startsWith('PK'):['doc','xls'].includes(ext)?bytes[0]===208&&bytes[1]===207:ext==='rtf'?head.startsWith('{\\rtf'):true;
    if(!correct)throw Error('Formato inválido: conteúdo não corresponde ao arquivo.');
    return {name:file.name,type:mime,size:file.size};
  }
  function attachmentStore(mode,id,blob) {
    return new Promise((resolve,reject)=>{
      const open=indexedDB.open('ecobella-v2-payment-files',1);
      open.onupgradeneeded=()=>open.result.createObjectStore('receipts');
      open.onerror=()=>reject(Error('Não foi possível abrir o armazenamento do comprovante.'));
      open.onsuccess=()=>{const db=open.result,tx=db.transaction('receipts',mode),store=tx.objectStore('receipts'),request=mode==='readonly'?store.get(id):store.put(blob,id);let result;
        request.onsuccess=()=>{result=request.result};tx.oncomplete=()=>{db.close();resolve(result)};tx.onerror=tx.onabort=()=>{db.close();reject(Error('Não foi possível guardar o comprovante. Tente novamente.'))};
      };
    });
  }
  function samplePDF(){
    const stream='BT /F1 16 Tf 40 720 Td (RECIBO SINTETICO - SEM VALIDADE) Tj 0 -30 Td (Ecobella - demonstracao local) Tj ET';
    const objects=['<< /Type /Catalog /Pages 2 0 R >>','<< /Type /Pages /Kids [3 0 R] /Count 1 >>','<< /Type /Page /Parent 2 0 R /MediaBox [0 0 595 842] /Resources << /Font << /F1 4 0 R >> >> /Contents 5 0 R >>','<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>',`<< /Length ${stream.length} >>\nstream\n${stream}\nendstream`];
    let pdf='%PDF-1.4\n',offsets=[0];objects.forEach((object,i)=>{offsets.push(pdf.length);pdf+=`${i+1} 0 obj\n${object}\nendobj\n`});const start=pdf.length;
    pdf+=`xref\n0 6\n0000000000 65535 f \n${offsets.slice(1).map(x=>String(x).padStart(10,'0')+' 00000 n \n').join('')}trailer\n<< /Size 6 /Root 1 0 R >>\nstartxref\n${start}\n%%EOF\n`;
    return new File([pdf],'comprovante-exemplo.pdf',{type:'application/pdf'});
  }
  function install(context) {
    const {$,esc,fmtMoney,fmtDate,clientName,modal,modalHeader,closeModal,render,notify,refresh,financial,actor,save,audit,validDate,key,getData,getClasses}=context;
    const money=n=>fmtMoney(n/100),allowed=id=>{refresh();return financial()&&actor()===id};
    const getPayment=id=>getData().payments.find(p=>p.id===id);
    const field=(label,name,type='text',value='',extra='')=>`<label class="field" for="payment-${name}">${label}<input class="input" id="payment-${name}" name="${name}" type="${type}" value="${esc(value)}" aria-describedby="payment-error" ${extra}></label>`;
    function picker(label,name,choices,value='',filter=false,disabled=false,searchable=false) {
      const selected=choices.find(([v])=>v===value)?.[1]||choices[0]?.[1]||'Selecione';
      return `<details class="payment-picker" data-pay-picker="${name}"><summary aria-label="${esc(label)}: ${esc(selected)}" ${disabled?'aria-disabled="true" tabindex="-1"':''}><span><span class="client-select-label">${esc(label)}</span><span class="payment-picker-value">${esc(selected)}</span></span><span aria-hidden="true">⌄</span></summary><input type="hidden" name="${name}" value="${esc(value)}"><div class="payment-picker-menu" role="group" aria-label="${esc(label)}">${searchable?`<input class="input" data-pay-option-search aria-label="Pesquisar opções de ${esc(label)}" placeholder="Pesquisar…" autocomplete="off">`:''}${choices.map(([v,text])=>`<button type="button" data-pay-choice="${name}" data-value="${esc(v)}" ${filter?'data-pay-filter':''} aria-pressed="${v===value}"><span>${esc(text)}</span><span aria-hidden="true">${v===value?'✓':''}</span></button>`).join('')}<p class="subtle payment-picker-empty" hidden>Nenhuma opção encontrada.</p></div></details>`;
    }
    function dueRows(clientId='') {
      return getClasses().filter(a=>!a.voidedAt&&!a.trial&&a.status!=='cancelled')
        .flatMap(a=>a.clientIds.filter(id=>!clientId||id===clientId).map(id=>({a,id,due:(cents(a.charges[id])||0)-coverage(getData(),getClasses(),a,id)})))
        .filter(x=>x.due>0).sort((x,y)=>(x.a.date+x.a.time).localeCompare(y.a.date+y.a.time)||x.a.id.localeCompare(y.a.id));
    }
    function lessonPicker(clientId,classId='') {
      const rows=clientId?dueRows(clientId):[];
      return picker('Aula','classId',[['',clientId?(rows.length?'Escolha a aula':'Nenhuma aula com saldo'):'Escolha o cliente primeiro'],...rows.map(({a,due})=>[a.id,`${fmtDate(a.date)} · ${a.time} · ${a.type} · ${money(due)}`])],classId,false,!rows.length);
    }
    function form(classId='',clientId='') {
      refresh();if(!financial())return;
      const selected=dueRows(clientId).find(x=>x.a.id===classId&&x.id===clientId);
      if(classId&&!selected){notify('Esta aula não tem saldo em aberto para o cliente.');return}
      const currentClient=selected?.id||context.filters().payClient||'';
      modal(modalHeader('Registrar pagamento','Pagamento de uma aula · demonstração com dados fictícios')+`<form id="payment-form" novalidate data-request-id="${crypto.randomUUID()}"><fieldset class="payment-fields"><div class="form-grid payment-main-fields"><div class="field full">${picker('Cliente','clientId',[['','Escolha o cliente'],...context.clients().map(c=>[c.id,c.name])],currentClient,false,false,true)}</div><div class="field full" id="payment-class-picker">${lessonPicker(currentClient,selected?.a.id)}</div><p class="payment-balance-summary full" id="payment-class-balance" role="status"></p>${field('Valor pago (R$)','amount','number',selected?(selected.due/100).toFixed(2):'','step="0.01" required')}${field('Data do pagamento','date','date',context.today,'required')}<div class="field">${picker('Forma de pagamento','method',methods.filter(m=>m!=='Cartão').map(m=>[m,m]),'Pix')}</div><div class="field" id="payment-installment-field" hidden>${field('Número de parcelas','installments','number','1','min="1" max="24" required')}</div></div><label class="check-line payment-other-payer"><input type="checkbox" name="otherPayer"> Outra pessoa pagou</label><div id="payment-payer-field" hidden>${field('Nome de quem pagou','payer','text','','maxlength="160"')}</div><section class="payment-receipt-section"><h3>Comprovante <span class="subtle">obrigatório</span></h3><label class="field" for="payment-file">Anexar arquivo<input id="payment-file" type="file" accept="${Object.keys(types).map(ext=>'.'+ext).join(',')}" aria-describedby="receipt-status payment-error"></label><p id="receipt-status" role="status">Nenhum arquivo selecionado.</p><p class="subtle">PDF, imagem ou documento · até 20 MiB. Preenchimento manual; extração automática não configurada.</p></section><details class="payment-more"><summary>Mais detalhes</summary><div class="form-grid">${field('Banco','bank','text','','maxlength="160"')}${field('Identificador da transação','identifier','text','','maxlength="160"')}${field('Observações','purposeNotes','text','','maxlength="500"')}</div><button type="button" class="text-link" data-example-receipt>Usar comprovante sintético PDF</button></details></fieldset><p id="payment-error" role="alert"></p><div class="dialog-actions payment-save-actions"><button type="button" class="button" data-close>Cancelar</button><button class="button primary" type="submit">Salvar pagamento</button></div></form>`,true);
      const f=$('#payment-form');f.contextClassId=selected?.a.id;f.paymentActor=actor();f.receiptFile=null;f.fileVersion=0;totals(f);
      (selected?$('#payment-amount'):$('[data-pay-picker="clientId"] summary',f)).focus();
    }
    function totals(f){
      const clientId=f.elements.clientId.value,classId=f.elements.classId.value,row=dueRows(clientId).find(x=>x.a.id===classId),amount=cents(f.elements.amount.value)||0;
      $('#payment-class-balance').textContent=row?`Saldo desta aula: ${money(row.due)}${amount>0&&amount<=row.due?' · Após este pagamento: '+money(row.due-amount):''}`:clientId&&!dueRows(clientId).length?'Este cliente não tem aulas com saldo em aberto.':'';
    }
    async function selectFile(f,file){const version=++f.fileVersion;f.receiptFile=null;$('#receipt-status').textContent='Validando arquivo…';try{const meta=await validateFile(file);if(version!==f.fileVersion||!f.isConnected||!allowed(f.paymentActor))return;f.receiptFile=file;f.receiptMeta=meta;$('#receipt-status').textContent=`${meta.name} · arquivo pronto.`}catch(error){if(version===f.fileVersion&&f.isConnected)$('#receipt-status').textContent=error.message}}
    function payload(f,recheck=true){
      const amountCents=cents(f.elements.amount.value),count=Number(f.elements.installments.value),method=f.elements.method.value,date=f.elements.date.value,clientId=f.elements.clientId.value,classId=f.elements.classId.value;
      if(!context.clients().some(c=>c.id===clientId))throw Error('Escolha o cliente do pagamento.');
      const lesson=getClasses().find(a=>a.id===classId);
      if(!lesson||lesson.voidedAt||lesson.trial||lesson.status==='cancelled'||!lesson.clientIds.includes(clientId))throw Error('Escolha uma aula válida desse cliente.');
      if(!amountCents)throw Error('Informe valor pago positivo, com até duas casas decimais.');
      if(!validDate(date)||!methods.includes(method))throw Error('Informe data e forma de pagamento válidas.');
      if(!Number.isInteger(count)||count<1||count>24||count>amountCents)throw Error('Parcelas: informe de 1 a 24, sem parcelas de valor zero.');
      if(count>1&&!['Cartão de crédito','Cartão'].includes(method))throw Error('Mais de uma parcela exige cartão de crédito.');
      if(recheck&&amountCents>(cents(lesson.charges[clientId])||0)-coverage(getData(),getClasses(),lesson,clientId))throw Error('O valor pago supera o saldo atual desta aula. Confira o valor antes de salvar.');
      const payer=f.elements.otherPayer.checked?f.elements.payer.value.trim():clientName(clientId);
      if(!payer)throw Error('Informe o nome da outra pessoa que pagou.');
      if(!f.receiptFile)throw Error('Anexe um comprovante válido antes de salvar, inclusive em dinheiro.');
      return {amountCents,date,method,installments:count,payer,purpose:'Aula',purposeNotes:f.elements.purposeNotes.value.trim(),bank:f.elements.bank.value.trim(),identifier:f.elements.identifier.value.trim(),allocations:[{classId,clientId,amountCents}]};
    }
    async function submit(f){
      if(f.dataset.pending==='true'||!allowed(f.paymentActor))return;
      const error=msg=>{if(f.isConnected){const el=$('#payment-error');el.textContent=msg;el.tabIndex=-1;el.focus()}};
      if(!navigator.locks)return error('Este navegador não oferece bloqueio local seguro. Use um navegador compatível.');
      f.dataset.pending='true';f.querySelector('fieldset').disabled=true;f.querySelector('[type="submit"]').disabled=true;
      try{await navigator.locks.request(key,async()=>{
        if(!allowed(f.paymentActor))throw Error('Acesso negado. Pagamento não registrado.');
        const requestId=f.dataset.requestId,existing=getData().payments.find(p=>p.requestId===requestId);
        const values=payload(f,!existing),file=f.receiptFile,attachment=await validateFile(file);
        attachment.sha256=Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',await file.arrayBuffer()))).map(x=>x.toString(16).padStart(2,'0')).join('');
        if(!allowed(f.paymentActor))throw Error('Acesso negado. Pagamento não registrado.');
        const canonical=JSON.stringify({author:f.paymentActor,...values,attachment});
        if(existing){if(existing.canonical!==canonical||existing.author!==f.paymentActor)throw Error('Esta operação já foi registrada com outros dados. Consulte o pagamento anterior antes de iniciar outro.');closeAfterSave(f,existing.id);return}
        await attachmentStore('readwrite',requestId,new Blob([file],{type:attachment.type}));
        if(!allowed(f.paymentActor))throw Error('Acesso negado. Pagamento não registrado.');
        // Recheck charges after asynchronous storage; the lock still owns this operation.
        payload(f);
        const p={id:'pay-'+requestId,requestId,canonical,...values,amount:values.amountCents/100,clientId:values.allocations[0]?.clientId||'',classId:values.allocations[0]?.classId||'',attachment:{id:requestId,...attachment},receipt:attachment.name,receiptConfirmed:true,status:'Registrado',author:actor(),installmentRows:values.installments>1?Array.from({length:values.installments},(_,i)=>({number:i+1,dueOn:addMonths(values.date,i),status:'expected',receivedOn:null,amountCents:Math.floor(values.amountCents/values.installments)+(i===values.installments-1?values.amountCents%values.installments:0)})):[]};
        const data=getData(),historyLength=data.history.length;data.payments.push(p);sync(data,getClasses());
        try{audit('payment',p.id,null,p,'Registrar pagamento fictício');save()}catch{data.payments.pop();data.history.length=historyLength;sync(data,getClasses());throw Error('Não foi possível salvar os dados locais. Campos e comprovante preservados; tente novamente.')}
        closeAfterSave(f,p.id);notify('Pagamento fictício registrado com comprovante local.');
      })}catch(e){error(e.message)}finally{f.dataset.pending='false';f.querySelector('fieldset').disabled=false;f.querySelector('[type="submit"]').disabled=false}
    }
    function closeAfterSave(f,id){f.dataset.pending='false';closeModal();if(f.contextClassId&&context.dialog.open)context.refreshClass(f.contextClassId);render();detail(id)}
    function detail(id){refresh();if(!financial())return;const p=getPayment(id);if(!p)return;const links=allocations(p),sum=links.reduce((s,a)=>s+(a.amountCents||0),0),total=p.amountCents||cents(p.amount)||0;
      modal(modalHeader(p.legacy?'Pagamento '+p.id.toUpperCase():'Detalhe do pagamento',`${fmtDate(p.date)} · ${esc(p.payer||clientName(p.clientId))}`)+`<dl class="info-grid">${[['Valor pago',money(total)],['Cliente',esc([...new Set(links.map(a=>clientName(a.clientId)))].join(', ')||'Não informado')],...(p.payer&&!links.some(a=>clientName(a.clientId)===p.payer)?[['Pago por',esc(p.payer)]]:[]),...(sum!==total?[['Valor vinculado (registro anterior)',money(sum)],['Valor livre (registro anterior)',money(total-sum)]]:[]),['Forma',esc(p.method)],['Data',fmtDate(p.date)],['Banco',esc(p.bank||'Não informado')],['Identificador',esc(p.identifier||'Não informado')],['Parcelas',String(p.installments)],['Comprovante',esc(p.receipt||'Indisponível')]].map(([label,value])=>`<div><dt>${label}</dt><dd>${value}</dd></div>`).join('')}</dl><div class="detail-section"><h3>${links.length===1?'Aula do pagamento':'Aulas do registro anterior'}</h3>${links.map(a=>{const c=getClasses().find(x=>x.id===a.classId);return `<div class="list-item"><div class="grow"><strong>${esc(clientName(a.clientId))} · ${money(a.amountCents||0)}</strong><span class="secondary">${c?fmtDate(c.date)+' · '+esc(c.type):'Aula indisponível'}</span></div><button class="text-link" data-detail="class:${esc(a.classId)}">Abrir aula</button></div>`}).join('')||'<p class="empty">Nenhuma aula vinculada. Valor livre.</p>'}</div><p class="note">Parcelas documentam o total registrado; não criam pagamentos adicionais.</p>${p.legacy?'<p class="note warn">Registro anterior da demonstração. O nome do comprovante legado não contém arquivo original. A cobertura anterior é preservada como referência legada, sem inventar pagamentos históricos.</p>':`<div class="detail-section"><h3>Histórico</h3><p>Registrado em ${esc(p.date)} · ${esc(getData().accounts.find(a=>a.id===p.author)?.name||'Conta fictícia')} · comprovante local confirmado.</p><button class="button" data-receipt="${esc(p.id)}">Abrir comprovante</button> <button class="button" data-download-receipt="${esc(p.id)}">Baixar original</button></div>`}${lifecycleDetail(p)}<div class="dialog-actions"><button class="button" data-close>${p.legacy?'Fechar':'Voltar'}</button></div>`,true);
    }
    function tabs(){const q=new URLSearchParams(context.filters());q.delete('payTab');const base=q.size?'?'+q:'';q.set('payTab','installments');return `<nav class="tabs" aria-label="Visões de pagamentos"><a class="button" href="#pagamentos${base}" ${context.filters().payTab!=='installments'?'aria-current="page"':''}>Pagamentos</a><a class="button" href="#pagamentos?${esc(q.toString())}" ${context.filters().payTab==='installments'?'aria-current="page"':''}>Parcelas</a></nav>`}
    function paymentRows(){const f=context.filters();return getData().payments.filter(p=>(!p.voidedAt||f.includeVoided==='yes')&&(!f.payClient||p.clientId===f.payClient||allocations(p).some(a=>a.clientId===f.payClient))&&(!f.payMethod||p.method===f.payMethod)&&(!f.payPurpose||(p.purpose||'Não informada')===f.payPurpose)&&(!f.payFromDate||p.date>=f.payFromDate)&&(!f.payToDate||p.date<=f.payToDate)&&(!f.paySearch||`${p.payer||''} ${allocations(p).map(a=>clientName(a.clientId)).join(' ')} ${p.method} ${p.id}`.toLowerCase().includes(f.paySearch.toLowerCase()))).sort((a,b)=>b.date.localeCompare(a.date)||a.id.localeCompare(b.id))}
    function exportRows(){if(!financial())return;context.csv('ecobella-v2-pagamentos-ficticios.csv',['Data','Cliente','Aula','Data da aula','Valor BRL','Forma de pagamento','Parcelas','Pago por outra pessoa','Comprovante','Situação','Motivo do estorno'],paymentRows().map(p=>{const links=allocations(p),names=[...new Set(links.map(a=>clientName(a.clientId)))],lessons=[...new Set(links.map(a=>a.classId))].map(id=>getClasses().find(a=>a.id===id));return[p.date,names.join(' / '),lessons.map(a=>a?.type||'Aula indisponível').join(' / '),lessons.map(a=>a?a.date+' '+a.time:'').join(' / '),((p.amountCents||cents(p.amount))/100).toFixed(2),p.method,p.installments,p.payer&&!names.includes(p.payer)?p.payer:'',p.receipt||'',p.voidedAt?'Estornado':'Registrado',p.voidReason||'']}))}
    function dateFilter(label,name){return `<label class="field">${label}<input class="input" type="date" data-filter="${name}" aria-label="${label}" value="${esc(context.filters()[name]||'')}"></label>`}
    function recordsPage(){
      const rows=paymentRows(),valid=rows.filter(p=>!p.voidedAt),f=context.filters(),keys=['paySearch','payClient','payMethod','payFromDate','payToDate','includeVoided','payPurpose'],active=keys.filter(k=>k!=='paySearch'&&f[k]).length;
      const controls=picker('Cliente','payClient',[['','Todos os clientes'],...context.clients().map(c=>[c.id,c.name])],f.payClient||'',true,false,true)
        +picker('Forma de pagamento','payMethod',[['','Todas as formas'],...methods.map(m=>[m,m])],f.payMethod||'',true)
        +`<label class="field payment-date">De<input class="input" type="date" data-pay-date="payFromDate" aria-label="Pagamentos de" value="${esc(f.payFromDate||'')}"></label><label class="field payment-date">Até<input class="input" type="date" data-pay-date="payToDate" aria-label="Pagamentos até" value="${esc(f.payToDate||'')}"></label>`
        +picker('Situação','includeVoided',[['','Sem estornados'],['yes','Incluir estornados']],f.includeVoided||'',true)
        +(f.payPurpose?picker('Finalidade anterior','payPurpose',[['','Todas'],...['Aula','Evento','Cavalo','Produto','Outro','Não informada'].map(x=>[x,x])],f.payPurpose,true):'');
      return context.head('Pagamentos','Consulte recebimentos e registre o pagamento de uma aula.',`<button class="button" data-export="pagamentos">↓ Exportar CSV</button><button class="button primary" data-new-payment>Registrar pagamento</button>`,'FINANCEIRO')+tabs()
        +`<div class="payment-metrics"><div><span class="label">Total recebido</span><strong>${money(valid.reduce((s,p)=>s+(p.amountCents||cents(p.amount)),0))}</strong><span class="subtle">No período filtrado · sem estornos</span></div><div><span class="label">Pagamentos</span><strong>${valid.length}</strong><span class="subtle">${rows.filter(p=>p.voidedAt).length?rows.filter(p=>p.voidedAt).length+' estornado(s) exibido(s)':'No período filtrado'}</span></div></div><section class="panel payments-panel"><div class="toolbar payments-toolbar"><input class="input search" data-filter="paySearch" aria-label="Buscar pagamentos" placeholder="Buscar cliente ou pagador" value="${esc(f.paySearch||'')}"><button class="button payment-filter-toggle" data-toggle-filters aria-controls="page-filters" aria-expanded="${context.filtersOpen()}">Filtros${active?' ('+active+')':''}</button><div class="payment-filter-fields" id="page-filters" ${context.filtersOpen()?'':'hidden'}>${controls}${keys.some(k=>f[k])?`<button class="text-link" data-clear-page="${keys.join(',')}">Limpar filtros</button>`:''}</div></div>`
        +context.table(['Data','Cliente','Aula','Valor','Forma','Comprovante','Situação',''],rows.map(p=>{
          const links=allocations(p),ids=[...new Set(links.map(a=>a.clientId).filter(Boolean))],names=ids.map(clientName),other=p.payer&&!names.includes(p.payer);
          return `<tr><td>${fmtDate(p.date)}</td><td>${ids.map(id=>`<button class="row-action" data-detail="client:${esc(id)}">${esc(clientName(id))}</button>`).join('<br>')||esc(p.payer||'Cliente não informado')}${other&&ids.length?`<span class="secondary">Pago por ${esc(p.payer)}</span>`:''}</td><td>${[...new Set(links.map(a=>a.classId).filter(Boolean))].map(id=>{const a=getClasses().find(x=>x.id===id);return `<button class="text-link" data-detail="class:${esc(id)}">${esc(a?.type||'Aula indisponível')}</button>${a?`<span class="secondary">${fmtDate(a.date,{day:'2-digit',month:'short'})} · ${esc(a.time)}</span>`:''}`}).join('<br>')||'<span class="subtle">Registro anterior sem aula</span>'}</td><td><strong>${money(p.amountCents||cents(p.amount))}</strong></td><td>${esc(p.method)}${p.installments>1?`<span class="secondary">${p.installments} parcelas</span>`:''}</td><td>${p.attachment&&p.receiptConfirmed?`<button class="text-link" data-receipt="${esc(p.id)}">Ver comprovante</button>`:'<span class="subtle">Não disponível</span>'}</td><td>${context.badge(p.voidedAt?'Estornado':'Registrado',p.voidedAt?'cancelled':'paid')}</td><td><button class="text-link" data-detail="payment:${esc(p.id)}" aria-label="Detalhes do pagamento de ${esc(names.join(', ')||p.payer)} em ${fmtDate(p.date)}">Detalhes →</button></td></tr>`;
        }).join(''),`${rows.length} pagamento(s) encontrado(s)`)+'</section>';
    }
    function installmentRows(){const f=context.filters();return getData().payments.filter(p=>!p.voidedAt&&p.installments>1&&['Cartão de crédito','Cartão'].includes(p.method)&&(!f.installmentClient||p.clientId===f.installmentClient||allocations(p).some(a=>a.clientId===f.installmentClient))).flatMap(p=>(p.installmentRows||[]).map(row=>({p,row}))).filter(({row})=>(!f.installmentFromDate||row.dueOn>=f.installmentFromDate)&&(!f.installmentToDate||row.dueOn<=f.installmentToDate)&&(!f.installmentStatus||(row.status||'unknown')===f.installmentStatus)).sort((a,b)=>(a.row.dueOn||'9999').localeCompare(b.row.dueOn||'9999')||a.p.id.localeCompare(b.p.id)||a.row.number-b.row.number)}
    const installmentStatus=row=>row.status==='received'?'Recebida':row.status==='expected'?'Prevista':'Não informado';
    function installmentButton(p,row){return row.dueOn&&['expected','received'].includes(row.status)&&!p.voidedAt?`<button class="text-link" data-settle-installment="${esc(p.id)}:${row.number}">${row.status==='received'?'Desmarcar recebida':'Marcar recebida'}</button>`:''}
    function installmentPage(){const rows=installmentRows(),total=status=>money(rows.filter(x=>x.row.status===status).reduce((sum,x)=>sum+x.row.amountCents,0));return context.head('Parcelas','Previsão e baixa manual de cartão parcelado. A baixa não cria receita.',`<button class="button" data-export-installments>Exportar parcelas</button>`,'FINANCEIRO')+tabs()+`<div class="metrics"><div class="panel metric"><span class="label">Previstas no recorte</span><div class="number">${total('expected')}</div></div><div class="panel metric"><span class="label">Recebidas no recorte</span><div class="number">${total('received')}</div></div></div><section class="panel">`+context.filterPanel(dateFilter('Vencimentos de','installmentFromDate')+dateFilter('Vencimentos até','installmentToDate')+context.selectFilter('Cliente das parcelas','installmentClient',context.clients().map(c=>[c.id,c.name]),'Todos os clientes')+context.selectFilter('Estado da parcela','installmentStatus',[['expected','Prevista'],['received','Recebida'],['unknown','Não informado']]),['installmentFromDate','installmentToDate','installmentClient','installmentStatus'])+context.table(['Pagamento / cliente','Parcela','Vencimento','Valor','Estado','Recebida em',''],rows.map(({p,row})=>`<tr data-installment-row="${esc(p.id)}:${row.number}"><td>${esc(p.payer||clientName(p.clientId))}<span class="secondary">${esc(p.id)}</span></td><td>${row.number} / ${p.installments}</td><td>${row.dueOn?fmtDate(row.dueOn):'Não informado'}</td><td>${money(row.amountCents)}</td><td>${installmentStatus(row)}</td><td>${row.receivedOn?fmtDate(row.receivedOn):'Não informada'}</td><td>${installmentButton(p,row)} <button class="text-link" data-detail="payment:${esc(p.id)}">Abrir pagamento</button></td></tr>`).join(''),`${rows.length} parcela(s) · CSV segue o recorte. Legado sem vencimentos não ganha datas ou recebimentos inventados.`)+'</section>'}
    function exportInstallments(){refresh();if(!financial())return;context.csv('ecobella-v2-parcelas-ficticias.csv',['Pagamento','Cliente','Parcela','Vencimento','Valor BRL','Estado','Recebida em'],installmentRows().map(({p,row})=>[p.id,p.payer||clientName(p.clientId),row.number,row.dueOn||'Não informado',(row.amountCents/100).toFixed(2),installmentStatus(row),row.receivedOn||'Não informada']))}
    function lifecycleDetail(p){const history=getData().history.filter(x=>x.kind==='payment'&&x.recordId===p.id&&['Baixa manual','Desmarcar recebida','Estornar pagamento'].includes(x.action));return `<p class="note">Cancelamento de aula não estorna o pagamento automaticamente.</p><div class="detail-section"><h3>Situação: ${p.voidedAt?'Estornado':'Registrado'}</h3><p>Finalidade: ${esc(p.purpose||'Não informada')}${p.purposeNotes?' · '+esc(p.purposeNotes):''}</p>${p.voidedAt?`<p class="note warn">Estornado em ${esc(p.voidedAt)} · ${esc(p.voidedBy)} · ${esc(p.voidReason)}. Vínculos e comprovante preservados como histórico; não quitam aulas.</p>${p.financialExceptions?.length?'<p class="note warn">Exceção financeira: resultado de aula concluída preservado.</p>':''}`:`<button class="button danger" data-void-payment="${esc(p.id)}">Estornar pagamento</button>`}</div><div class="detail-section"><h3>Parcelas previstas</h3>${p.legacy?'<p class="note">Vencimentos e recebimentos anteriores não informados.</p>':p.installments<=1?'<p>Não parcelado.</p>':context.table(['Parcela','Vencimento','Valor','Estado','Recebida em',''],(p.installmentRows||[]).map(row=>`<tr><td>${row.number} / ${p.installments}</td><td>${row.dueOn?fmtDate(row.dueOn):'Não informado'}</td><td>${money(row.amountCents)}</td><td>${installmentStatus(row)}</td><td>${row.receivedOn?fmtDate(row.receivedOn):'Não informada'}</td><td>${installmentButton(p,row)}</td></tr>`).join(''))}</div>${history.length?`<div class="detail-section"><h3>Histórico financeiro</h3>${history.map(x=>`<p>${esc(x.action)} · ${esc(x.date)} · ${esc(x.author)}${x.after?.voidReason?' · '+esc(x.after.voidReason):''}</p>`).join('')}</div>`:''}`}
    function lifecycleForm(id,number){refresh();if(!financial())return;const p=getPayment(id);if(!p||p.voidedAt)return;const row=number?p.installmentRows?.find(x=>x.number===number):null;if(number&&(!row?.dueOn||!['expected','received'].includes(row.status)))return;const undo=row?.status==='received';modal(modalHeader(number?(undo?'Desmarcar recebida':'Baixa manual de parcela'):'Estornar pagamento','Simulação local · confira antes de confirmar')+`<form id="${number?'settle-form':'void-payment-form'}" data-request-id="${crypto.randomUUID()}" novalidate><fieldset class="payment-fields">${number?`<p>Parcela ${number} / ${p.installments} · ${money(row.amountCents)}. ${undo?'O recebimento será removido.':'A baixa altera somente o estado desta parcela.'} Não cria pagamento ou receita.</p>${undo?'':field('Recebida em','receivedOn','date',context.today,'required')}`:`<p>Valor do registro: ${money(p.amountCents||cents(p.amount))}. Estornar retira a cobertura válida dos vínculos abaixo. Não exclui comprovante, vínculos ou resultado.</p>${allocations(p).map(link=>{const a=getClasses().find(x=>x.id===link.classId);return `<p>${esc(clientName(link.clientId))} · aula ${esc(link.classId)} · ${money(link.amountCents||0)} · ${a?.status==='done'?'Exceção financeira: resultado será preservado.':'A cobrança volta a ficar pendente; a aula não será concluída sem quitação.'}</p>`}).join('')}<label class="field" for="void-reason">Motivo do estorno<textarea class="input" id="void-reason" name="reason" maxlength="500" aria-describedby="lifecycle-error" required></textarea></label>`}</fieldset><p id="lifecycle-error" role="alert"></p><div class="dialog-actions"><button class="button" type="button" data-close>${number?'Cancelar':'Cancelar estorno'}</button><button class="button danger" type="submit">${number?(undo?'Confirmar remoção da baixa':'Confirmar baixa manual'):'Confirmar estorno fictício'}</button></div></form>`,true);const f=$('#'+(number?'settle-form':'void-payment-form'));f.paymentActor=actor();f.paymentId=id;f.installmentNumber=number;f.undo=undo;f.querySelector('input,textarea')?.focus()}
    function legacyLinks(p){const links=allocations(p);if(!links.length)throw Error('Legado sem vínculo atribuível; estorno não pode inventar cobertura.');for(const link of links){const a=getClasses().find(x=>x.id===link.classId),baseline=getData().legacyCoverage[link.classId]?.[link.clientId]||0,total=getData().payments.filter(x=>x.legacy).flatMap(allocations).filter(x=>x.classId===link.classId&&x.clientId===link.clientId).reduce((sum,x)=>sum+(x.amountCents||0),0);if(!a||!a.clientIds.includes(link.clientId)||!Number.isSafeInteger(link.amountCents)||link.amountCents<=0||total>baseline)throw Error('Cobertura legada ambígua: não é possível atribuir este estorno sem alterar outros vínculos.')}return structuredClone(links)}
    async function submitLifecycle(f){if(f.dataset.pending==='true'||!allowed(f.paymentActor))return;const error=msg=>{if(f.isConnected)$('#lifecycle-error').textContent=msg};if(!navigator.locks)return error('Navegador sem bloqueio local seguro.');const reason=f.elements.reason?.value.trim(),receivedOn=f.elements.receivedOn?.value||null;if(!f.installmentNumber&&!reason)return error('Informe o motivo do estorno.');if(f.installmentNumber&&!f.undo&&!validDate(receivedOn))return error('Informe a data de recebimento válida.');f.dataset.pending='true';f.querySelector('fieldset').disabled=true;f.querySelector('[type="submit"]').disabled=true;
      try{await navigator.locks.request(key,async()=>{if(!allowed(f.paymentActor))throw Error('Acesso negado. Alteração não registrada.');const data=getData(),p=getPayment(f.paymentId);if(!p)throw Error('Pagamento indisponível.');const values={paymentId:p.id,number:f.installmentNumber||null,undo:!!f.undo,reason:reason||null,receivedOn,author:f.paymentActor},canonical=JSON.stringify(values),commands=data.financialCommands||[],prior=commands.find(x=>x.requestId===f.dataset.requestId);if(prior){if(prior.canonical!==canonical)throw Error('Operação já registrada com outros dados. Consulte o registro anterior.');finishLifecycle(f,p.id);return}let row;if(f.installmentNumber){row=p.installmentRows?.find(x=>x.number===f.installmentNumber);if(p.voidedAt||!row?.dueOn)throw Error('Parcela indisponível para baixa.');if((f.undo&&row.status==='expected')||(!f.undo&&row.status==='received'&&row.receivedOn===receivedOn)){finishLifecycle(f,p.id);return}if((f.undo&&row.status!=='received')||(!f.undo&&row.status!=='expected'))throw Error('Parcela alterada em outra aba. Revise o recebimento atual.')}else if(p.voidedAt){if(p.voidReason!==reason)throw Error('Pagamento já estornado com outro motivo.');finishLifecycle(f,p.id);return}
        const before=structuredClone(p),historyLength=data.history.length,oldCommands=data.financialCommands,classesBefore=getClasses().map(a=>[a,structuredClone(a.financialExceptions)]);if(!row&&p.legacy)p.legacyRefundLinks=legacyLinks(p);const now=new Date().toISOString();if(row){row.status=f.undo?'expected':'received';row.receivedOn=f.undo?null:receivedOn;row.receivedBy=f.undo?null:data.accounts.find(a=>a.id===f.paymentActor)?.name}else{p.voidedAt=now;p.voidReason=reason;p.voidedBy=data.accounts.find(a=>a.id===f.paymentActor)?.name||'Conta fictícia';p.financialExceptions=[];for(const classId of new Set(allocations(p).map(x=>x.classId))){const a=getClasses().find(x=>x.id===classId);if(a?.status==='done'){const exception={paymentId:p.id,date:now,author:p.voidedBy,reason};(a.financialExceptions||=[]).push(exception);p.financialExceptions.push(classId)}}}data.financialCommands=[...commands,{requestId:f.dataset.requestId,canonical}];sync(data,getClasses());try{audit('payment',p.id,before,p,row?(f.undo?'Desmarcar recebida':'Baixa manual'):'Estornar pagamento');save()}catch{for(const k of Object.keys(p))delete p[k];Object.assign(p,before);data.history.length=historyLength;if(oldCommands)data.financialCommands=oldCommands;else delete data.financialCommands;for(const[a,exceptions]of classesBefore){if(exceptions)a.financialExceptions=exceptions;else delete a.financialExceptions}sync(data,getClasses());throw Error('Não foi possível salvar os dados locais. Campos e operação preservados; tente novamente.')}finishLifecycle(f,p.id);notify(row?'Estado da parcela registrado. Receita inalterada.':'Estorno fictício registrado; histórico preservado.');})}catch(e){error(e.message)}finally{f.dataset.pending='false';f.querySelector('fieldset').disabled=false;f.querySelector('[type="submit"]').disabled=false}}
    function finishLifecycle(f,id){f.dataset.pending='false';closeModal();render();if(context.dialog.open)context.replacePayment(id)}
    const blobURLs=new Set();
    function cleanup(){for(const url of blobURLs)URL.revokeObjectURL(url);blobURLs.clear()}
    async function receipt(id,download=false){
      refresh();if(!financial())return;const who=actor(),p=getPayment(id);if(!p?.attachment){notify('Comprovante original indisponível neste registro legado.');return}
      try{const blob=await attachmentStore('readonly',p.attachment.id);if(!allowed(who))return;if(!blob)throw Error('Comprovante local indisponível. Não há arquivo original para baixar.');
        const file=new File([blob],p.attachment.name,{type:p.attachment.type}),meta=await validateFile(file);if(!allowed(who))return;
        const hash=Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',await blob.arrayBuffer()))).map(x=>x.toString(16).padStart(2,'0')).join('');if(!allowed(who))return;if(hash!==p.attachment.sha256)throw Error('Comprovante local alterado ou incompleto.');
        const url=URL.createObjectURL(new Blob([blob],{type:meta.type}));blobURLs.add(url);
        if(download){const a=document.createElement('a');a.href=url;a.download=meta.name;a.rel='noreferrer';document.body.append(a);a.click();a.remove();setTimeout(()=>{URL.revokeObjectURL(url);blobURLs.delete(url)},1000);return}
        // Only a verified PDF Blob reaches the native PDF viewer, never active HTML/SVG.
        const preview=meta.type==='application/pdf'?`<p class="subtle">Prévia pelo leitor PDF do navegador. Caso não apareça, baixe o original.</p><iframe class="receipt-preview" title="Comprovante PDF" referrerpolicy="no-referrer" src="${url}"></iframe>`:meta.type.startsWith('image/')?`<img class="receipt-image" alt="Comprovante fictício ${esc(meta.name)}" src="${url}">`:'<p class="note">Prévia indisponível para este formato. Baixe o arquivo original.</p>';
        modal(modalHeader('Comprovante fictício',esc(meta.name))+preview+`<div class="dialog-actions"><button class="button" data-download-receipt="${esc(id)}">Baixar original</button><button class="button" data-close>Voltar ao pagamento</button></div>`,true);
      }catch(e){notify(e.message)}
    }
    document.addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;if(b.hasAttribute('data-new-payment'))form(...(b.dataset.newPayment||'').split(':'));if(b.hasAttribute('data-example-receipt')&&financial()){const f=b.closest('form');if(f&&!f.querySelector('fieldset').disabled)selectFile(f,samplePDF())}if(b.dataset.voidPayment)lifecycleForm(b.dataset.voidPayment);if(b.dataset.settleInstallment){const [id,number]=b.dataset.settleInstallment.split(':');lifecycleForm(id,Number(number))}if(b.hasAttribute('data-export-installments'))exportInstallments();if(b.dataset.receipt)receipt(b.dataset.receipt);if(b.dataset.downloadReceipt)receipt(b.dataset.downloadReceipt,true)});
    document.addEventListener('click',e=>{
      const choice=e.target.closest('[data-pay-choice]'),summary=e.target.closest('.payment-picker>summary'),f=e.target.closest('#payment-form');
      if((choice||summary)&&f?.querySelector('fieldset').disabled){e.preventDefault();return}
      if(summary){if(summary.getAttribute('aria-disabled')==='true'){e.preventDefault();return}document.querySelectorAll('.payment-picker[open]').forEach(p=>{if(p!==summary.parentElement)p.open=false})}
      if(!e.target.closest('.payment-picker'))document.querySelectorAll('.payment-picker[open]').forEach(p=>p.open=false);
      if(!choice)return;
      const name=choice.dataset.payChoice,value=choice.dataset.value,p=choice.closest('.payment-picker');
      if(choice.hasAttribute('data-pay-filter')){context.filters()[name]=value;render();$(`[data-pay-picker="${name}"] summary`)?.focus();return}
      $('input[type="hidden"]',p).value=value;
      const label=$('.client-select-label',p).textContent,text=choice.querySelector('span').textContent;
      $('.payment-picker-value',p).textContent=text;$('summary',p).setAttribute('aria-label',`${label}: ${text}`);
      p.querySelectorAll('[data-pay-choice]').forEach(b=>{b.setAttribute('aria-pressed',String(b===choice));b.lastElementChild.textContent=b===choice?'✓':''});p.open=false;$('summary',p).focus();
      if(!f)return;
      if(name==='clientId'){$('#payment-class-picker').innerHTML=lessonPicker(value);f.elements.amount.value=''}
      if(name==='classId'){const row=dueRows(f.elements.clientId.value).find(x=>x.a.id===value);f.elements.amount.value=row?(row.due/100).toFixed(2):''}
      if(name==='method'){$('#payment-installment-field').hidden=value!=='Cartão de crédito';if(value!=='Cartão de crédito')f.elements.installments.value='1'}
      $('#payment-error').textContent='';totals(f);
    });
    document.addEventListener('keydown',e=>{
      const p=e.target.closest('.payment-picker');if(!p)return;
      if(p.closest('fieldset')?.disabled){e.preventDefault();return}
      const summary=$('summary',p);
      if(e.key==='Escape'&&p.open){e.preventDefault();e.stopPropagation();p.open=false;summary.focus();return}
      if(!['ArrowDown','ArrowUp','Home','End'].includes(e.key)||e.target.matches('[data-pay-option-search]'))return;
      if(summary.getAttribute('aria-disabled')==='true')return;
      const items=[...p.querySelectorAll('[data-pay-choice]')].filter(b=>!b.hidden);if(!items.length)return;
      e.preventDefault();p.open=true;const index=items.indexOf(e.target),next=e.key==='Home'?0:e.key==='End'?items.length-1:e.key==='ArrowDown'?(index+1)%items.length:(index-1+items.length)%items.length;items[next].focus();
    });
    document.addEventListener('focusin',e=>document.querySelectorAll('.payment-picker[open]').forEach(p=>{if(!p.contains(e.target))p.open=false}));
    document.addEventListener('change',e=>{if(e.target.dataset.payDate){const key=e.target.dataset.payDate;context.filters()[key]=e.target.value;render();$(`[data-pay-date="${key}"]`)?.focus()}});
    document.addEventListener('input',e=>{if(!e.target.hasAttribute('data-pay-option-search'))return;const p=e.target.closest('.payment-picker'),q=e.target.value.toLocaleLowerCase('pt-BR');p.querySelectorAll('[data-pay-choice]').forEach(b=>b.hidden=!b.textContent.toLocaleLowerCase('pt-BR').includes(q));$('.payment-picker-empty',p).hidden=!!p.querySelector('[data-pay-choice]:not([hidden])')});
    document.addEventListener('change',e=>{if(e.target.id==='payment-file')selectFile(e.target.closest('form'),e.target.files[0]);if(e.target.name==='otherPayer'){$('#payment-payer-field').hidden=!e.target.checked;if(e.target.checked)$('#payment-payer').focus()}});
    document.addEventListener('input',e=>{if(e.target.closest('#settle-form,#void-payment-form'))$('#lifecycle-error').textContent='';const f=e.target.closest('#payment-form');if(f){$('#payment-error').textContent='';totals(f)}});
    document.addEventListener('submit',e=>{if(['settle-form','void-payment-form'].includes(e.target.id)){e.preventDefault();submitLifecycle(e.target)}if(e.target.id==='payment-form'){e.preventDefault();submit(e.target)}});
    context.dialog.addEventListener('close',cleanup);context.profileSelect.addEventListener('change',cleanup);window.addEventListener('pagehide',cleanup);
    return {form,detail,receipt,cleanup,paymentRows,recordsPage,installmentPage,exportRows};
  }
  globalThis.EcobellaPayments={cents,allocations,initialize,coverage,sync,validPayment,validateFile,samplePDF,install};
})();
