/* Seven existing report projections, derived only from fictional local records. */
(() => {
  'use strict';
  const definitions={
    aulas:{title:'Relatório de aulas',lead:'Uma linha por aula: modalidade, instrutor, duração, participantes, presença e uso registrado.',columns:[['date','Data','date'],['type','Tipo'],['instructor','Instrutor'],['status','Situação'],['duration','Duração (min)'],['participants','Participantes'],['present','Presentes'],['horses','Cavalos'],['trial','Experimental']],filters:['type','instructor','status','client','horse']},
    aderencia:{title:'Planejado x realizado',lead:'Compara datas previstas conhecidas com a ocorrência atual, mantendo a identidade de cada aula.',columns:[['date','Data prevista','date'],['type','Tipo'],['instructor','Instrutor'],['outcome','Desfecho']],filters:['type','instructor']},
    instrutores:{title:'Carga dos instrutores',lead:'Aulas concluídas, alunos distintos, duração registrada, capacidade e sobreposições por dia.',columns:[['date','Dia','date'],['instructor','Instrutor'],['classes','Aulas'],['students','Alunos atendidos'],['minutes','Minutos ministrados'],['capacity','Capacidade (h)'],['usage','Uso (%)'],['overlap','Sobrepostas']],filters:['instructor']},
    cavalos:{title:'Uso dos cavalos',lead:'Uso efetivamente registrado por cavalo e dia; aulas distintas e minutos por registro de uso.',columns:[['date','Dia','date'],['horse','Cavalo'],['classes','Aulas'],['minutes','Minutos'],['types','Tipos de aula'],['participants','Participantes']],filters:['horse']},
    clientes:{title:'Atividade dos clientes',lead:'Aulas, faltas e última aula no período. Participações ativas e origem mostram o estado atual.',columns:[['name','Cliente'],['status','Situação'],['schedules','Participações recorrentes ativas'],['classes','Aulas realizadas'],['absences','Faltas'],['last','Última aula','date'],['origin','Campanha de origem']],filters:['clientStatus','campaign']},
    cancelamentos:{title:'Cancelamentos',lead:'Somente aulas canceladas; anulações não entram neste relatório.',columns:[['date','Data','date'],['type','Tipo'],['instructor','Instrutor'],['reason','Motivo'],['notes','Detalhe'],['clients','Clientes afetados']],filters:['reason','type','instructor']},
    financeiro:{title:'Relatório financeiro',lead:'Pagamentos válidos e estornados. Totais consideram cada registro válido uma única vez.',columns:[['date','Data','date'],['payer','Pagador'],['amount','Valor','money'],['method','Forma'],['purpose','Para que'],['installments','Parcelas'],['allocated','Vinculado','money'],['free','Não vinculado','money'],['status','Situação']],filters:['method','purpose','client']}
  };
  const status={planned:'Planejada',done:'Realizada',cancelled:'Cancelada'};
  const reasonOptions=['Chuva','Outro fator climático','Ausência do aluno','Ausência do instrutor','Cavalo indisponível','Estrutura','Outro'];
  const entityLabels={client:'Clientes',class:'Aulas',horse:'Cavalos',team:'Equipe',modality:'Modalidades',campaign:'Campanhas',payment:'Pagamentos',access:'Acessos'};
  function install(c){
    const {$,esc,head,filterPanel,table,csv,notify,render,route}=c;
    const data=()=>c.getData(),classes=()=>c.getClasses(),filters=()=>c.filters();
    const operational=()=>c.allowed(),financial=()=>c.financial();
    const date=value=>value?c.fmtDate(value,{day:'2-digit',month:'2-digit',year:'numeric'}):'Não informado';
    const spDate=value=>{const time=new Date(value);if(Number.isNaN(time.getTime()))return null;return new Intl.DateTimeFormat('en-CA',{timeZone:'America/Sao_Paulo'}).format(time)};
    const now=()=>spDate(new Date().toISOString());
    const stamp=value=>{const time=new Date(value);return Number.isNaN(time.getTime())?'Não informado':new Intl.DateTimeFormat('pt-BR',{dateStyle:'short',timeStyle:'short',timeZone:'America/Sao_Paulo'}).format(time)};
    const options=(items,selected,all='Todos')=>`<option value="">${all}</option>`+items.map(([value,label])=>`<option value="${esc(value)}" ${selected===String(value)?'selected':''}>${esc(label)}</option>`).join('');
    const select=(label,key,items,all)=>`<label class="field">${label}<select class="select" data-report-filter="${key}" aria-label="${label}">${options(items,filters()[key],all)}</select></label>`;
    function range(audit=false){const f=filters(),prefix=audit?'audit':'report',until=audit?now():c.today;f[prefix+'FromDate']||=c.addDays(until,-29);f[prefix+'ToDate']||=until;c.syncRoute();return{from:f[prefix+'FromDate'],to:f[prefix+'ToDate'],valid:c.validDate(f[prefix+'FromDate'])&&c.validDate(f[prefix+'ToDate'])&&f[prefix+'FromDate']<=f[prefix+'ToDate']}}
    const within=(value,r)=>value&&value>=r.from&&value<=r.to;
    const participantRows=a=>a.result?.participants||null;
    const horseRows=a=>a.result?.horses||[];
    const absent=a=>participantRows(a)?.filter(p=>['absent','justified_absence'].includes(p.attendance))||null;
    const kindMatches=(a,f)=>!f.reportType||a.modalityId===f.reportType;
    const instructorMatches=(a,f)=>!f.reportInstructor||a.instructor===f.reportInstructor;
    const instructorName=id=>data().team.find(t=>t.id===id)?.name||'Não informado';
    const horseName=id=>data().horses.find(h=>h.id===id)?.name||'Não informado';
    const clientName=id=>data().clients.find(p=>p.id===id)?.name||'Não informado';
    const campaignName=id=>data().campaigns.find(p=>p.id===id)?.name||'Não informado';
    const link=(kind,id,label)=>({kind,id,label});
    const classLinks=rows=>rows.map(a=>link('class',a.id,'Abrir aula '+a.id));
    const unique=items=>[...new Set(items)];
    const descending=(a,b)=>String(b.date||'').localeCompare(String(a.date||''))||String(a.id).localeCompare(String(b.id));
    function classReport(f,r){return classes().filter(a=>!a.voidedAt&&within(a.date,r)&&kindMatches(a,f)&&instructorMatches(a,f)&&(!f.reportStatus||a.status===f.reportStatus)&&(!f.reportClient||a.clientIds.includes(f.reportClient))&&(!f.reportHorse||horseRows(a).some(h=>h.horseId===f.reportHorse))).map(a=>({id:a.id,date:a.date,type:a.type,instructor:instructorName(a.instructor),status:status[a.status]||'Não informado',duration:a.duration,participants:a.clientIds.length,present:participantRows(a)?`${a.result.participants.filter(x=>x.attendance==='present').length}/${a.result.participants.length}`:'Não informado',horses:a.result?horseRows(a).length:'Não informado',trial:a.trial?'Sim':'Não',links:classLinks([a])})).sort(descending)}
    function adherence(f,r){return classes().map(a=>{const history=data().history.filter(x=>x.kind==='class'&&x.recordId===a.id).sort((x,y)=>x.date.localeCompare(y.date)||x.id.localeCompare(y.id));const creation=history.find(x=>x.action==='Planejar aula')?.after,original=creation||history.find(x=>x.before?.date)?.before||a;return{id:a.id,date:original.date,type:original.type||a.type,instructor:instructorName(original.instructor||a.instructor),modalityId:original.modalityId||a.modalityId,instructorId:original.instructor||a.instructor,outcome:a.voidedAt?'Anulada · sem resultado válido':a.date!==original.date?'Sem registro na data prevista':a.status==='planned'?'Sem resultado':status[a.status],links:classLinks([a])}}).filter(a=>within(a.date,r)&&(!f.reportType||a.modalityId===f.reportType)&&(!f.reportInstructor||a.instructorId===f.reportInstructor)).sort((a,b)=>a.date.localeCompare(b.date)||a.id.localeCompare(b.id))}
    function workload(f,r){const delivered=classes().filter(a=>!a.voidedAt&&a.status==='done'&&within(a.date,r)&&instructorMatches(a,f)),groups=new Map();for(const a of delivered){const id=a.instructor+':'+a.date;if(!groups.has(id))groups.set(id,[]);groups.get(id).push(a)}return[...groups.entries()].map(([id,rows])=>{const person=data().team.find(t=>t.id===rows[0].instructor),raw=person?.dailyHourCapacity??(/^\d+(?:[.,]\d+)?h\s*\/\s*dia$/.test(person?.capacity||'')?Number(person.capacity.split('h')[0].replace(',','.')):null),capacity=Number.isFinite(raw)&&raw>0?raw:null,minutes=rows.every(a=>Number.isFinite(a.duration))?rows.reduce((sum,a)=>sum+a.duration,0):null,start=a=>{const [hour,minute]=a.time.split(':').map(Number);return hour*60+minute},overlap=rows.filter(a=>rows.some(b=>a.id!==b.id&&start(a)<start(b)+b.duration&&start(b)<start(a)+a.duration)).length;return{id,date:rows[0].date,instructor:person?.name||'Não informado',classes:rows.length,students:unique(rows.flatMap(a=>a.clientIds)).length,minutes,capacity,usage:capacity&&minutes!==null?Math.round(minutes*10000/(capacity*60))/100:null,overlap,links:classLinks(rows)}}).sort(descending)}
    function usage(f,r){const groups=new Map();for(const a of classes().filter(a=>!a.voidedAt&&a.status==='done'&&within(a.date,r)))for(const h of horseRows(a)){if(f.reportHorse&&h.horseId!==f.reportHorse)continue;const id=h.horseId+':'+a.date;if(!groups.has(id))groups.set(id,[]);groups.get(id).push({a,h})}return[...groups.entries()].map(([id,rows])=>{const values=rows.map(({a,h})=>h.usedMinutes??a.duration);return{id,date:rows[0].a.date,horse:horseName(rows[0].h.horseId),classes:unique(rows.map(x=>x.a.id)).length,minutes:values.every(Number.isFinite)?values.reduce((s,n)=>s+n,0):null,reference:rows.some(x=>x.h.usedMinutes==null),types:unique(rows.map(x=>x.a.type)).join(' / '),participants:unique(rows.map(x=>x.h.participantClientId).filter(Boolean)).map(clientName).join(' / ')||'Apoio, sem cavaleiro',links:classLinks(unique(rows.map(x=>x.a.id)).map(id=>classes().find(a=>a.id===id)))}}).sort(descending)}
    function activity(f,r){return data().clients.filter(p=>(!f.reportClientStatus||p.status===f.reportClientStatus)&&(!f.reportCampaign||p.origin?.type==='campaign'&&p.origin.campaignId===f.reportCampaign)).map(p=>{const rows=classes().filter(a=>!a.voidedAt&&a.status==='done'&&a.clientIds.includes(p.id)&&within(a.date,r)),known=rows.flatMap(a=>absent(a)||[]),missing=rows.some(a=>!participantRows(a)),participations=data().participations.filter(s=>s.clientId===p.id&&!s.endsOn),oldSeries=classes().filter(a=>!a.voidedAt&&a.series&&a.status==='planned'&&a.clientIds.includes(p.id));return{id:p.id,name:p.name,status:p.status,schedules:unique([...participations.map(x=>x.series),...oldSeries.filter(a=>!data().participations.some(s=>s.series===a.series&&s.clientId===p.id)).map(a=>a.series)]).length,classes:rows.length,absences:missing?(known.filter(x=>x.clientId===p.id).length+' · legado não informado'):known.filter(x=>x.clientId===p.id).length,last:rows.map(a=>a.date).sort().at(-1)||null,origin:p.origin?.type==='campaign'?campaignName(p.origin.campaignId):'Não informada',links:[link('client',p.id,'Abrir cliente '+p.name)]}}).sort((a,b)=>a.name.localeCompare(b.name,'pt-BR')||a.id.localeCompare(b.id))}
    function cancellations(f,r){return classes().filter(a=>!a.voidedAt&&a.status==='cancelled'&&within(a.date,r)&&kindMatches(a,f)&&instructorMatches(a,f)&&(!f.reportReason||(a.cancelReason||a.reason?.split(' · ')[0])===f.reportReason)).map(a=>({id:a.id,date:a.date,type:a.type,instructor:instructorName(a.instructor),reason:a.cancelReason||a.reason||'Não informado',notes:a.cancelDetails||a.reason?.split(' · ').slice(1).join(' · ')||'Não informado',clients:a.clientIds.map(clientName).join(' / '),links:classLinks([a])})).sort(descending)}
    function financialRows(f,r){return data().payments.filter(p=>within(p.date,r)&&(!f.reportMethod||p.method===f.reportMethod)&&(!f.reportPurpose||p.purpose===f.reportPurpose)&&(!f.reportClient||EcobellaPayments.allocations(p).some(a=>a.clientId===f.reportClient))).map(p=>{const amount=p.amountCents??EcobellaPayments.cents(p.amount),allocations=EcobellaPayments.allocations(p),allocated=allocations.reduce((sum,a)=>sum+(a.amountCents||0),0);return{id:p.id,date:p.date,payer:p.payer||'Não informado (legado)',amount,method:p.method||'Não informado',purpose:p.purpose||'Não informada',installments:p.installments||1,allocated,free:amount-allocated,status:p.voidedAt?'Estornado':'Válido',valid:!p.voidedAt&&(p.legacy||EcobellaPayments.validPayment(p,classes())),share:f.reportClient?allocations.filter(a=>a.clientId===f.reportClient).reduce((s,a)=>s+(a.amountCents||0),0):allocated,links:[link('payment',p.id,'Abrir pagamento '+p.id)]}}).sort(descending)}
    const queries={aulas:classReport,aderencia:adherence,instrutores:workload,cavalos:usage,clientes:activity,cancelamentos:cancellations,financeiro:financialRows};
    function reportFilters(kind){const def=definitions[kind],f=filters();const items={type:['Tipo','reportType',data().modalities.map(x=>[x.id,x.name])],instructor:['Instrutor','reportInstructor',data().team.filter(x=>x.role.startsWith('Instrutor')).map(x=>[x.id,x.name])],status:['Situação','reportStatus',Object.entries(status)],client:[kind==='financeiro'?'Cliente vinculado':'Cliente','reportClient',data().clients.map(x=>[x.id,x.name])],horse:['Cavalo','reportHorse',data().horses.map(x=>[x.id,x.name])],clientStatus:['Situação','reportClientStatus',unique(data().clients.map(x=>x.status)).map(x=>[x,x])],campaign:['Campanha','reportCampaign',data().campaigns.map(x=>[x.id,x.name])],reason:['Motivo','reportReason',reasonOptions.map(x=>[x,x])],method:['Forma','reportMethod',['Pix','Dinheiro','Boleto','Cartão de débito','Cartão de crédito','Cartão'].map(x=>[x,x])],purpose:['Para que','reportPurpose',['Aula','Evento','Cavalo','Produto','Outro'].map(x=>[x,x])]};return dates('report',f)+def.filters.map(key=>select(...items[key])).join('')}
    function dates(prefix,f){return `<label class="field">De<input class="input" type="date" data-report-filter="${prefix}FromDate" aria-label="De" value="${esc(f[prefix+'FromDate'])}"></label><label class="field">Até<input class="input" type="date" data-report-filter="${prefix}ToDate" aria-label="Até" value="${esc(f[prefix+'ToDate'])}"></label>`}
    const notes={aulas:'Presenças e uso de cavalos do legado sem resultado individual ficam Não informado. A duração é a duração registrada da aula; Cavalos conta registros de uso.',aderencia:'Datas previstas vêm da criação ou do registro anterior mais antigo; sem histórico, usa a data persistida como referência local. O legado não contém a definição completa da recorrência; nenhuma data ausente é presumida.',instrutores:'Minutos ministrados usam a duração registrada das aulas concluídas. Sobreposições contam cada aula envolvida uma vez. Capacidade e descanso são informações; não bloqueiam agenda.',cavalos:'Somente usos registrados entram na soma. O legado com apenas cavalo de planejamento não representa execução. Quando minutos do uso estão não informados, a duração da aula é referência; não são minutos efetivos confirmados.',clientes:'Faltas incluem ausente e ausência justificada somente em aulas realizadas no período. Presença legada desconhecida não é presumida. Participações ativas e origem são o estado atual.',cancelamentos:'Anulações permanecem no histórico, sem serem somadas como cancelamentos.',financeiro:'Cliente vinculado filtra alocações, não identifica quem pagou. Cada pagamento aparece uma vez, mesmo coletivo. Vinculado ao cliente soma apenas sua parte; livre pertence ao pagamento. Registros estornados não entram nos totais.'};
    function display(value,format){if(value==null)return'Não informado';if(format==='date')return date(value);if(format==='money')return c.fmtMoney(value/100);return String(value)}
    function pager(total,size,audit=false){const f=filters(),key=audit?'auditPage':'reportPage',pages=Math.max(1,Math.ceil(total/size)),page=Math.min(pages,Math.max(1,Number(f[key])||1));if(f[key]&&Number(f[key])!==page){f[key]=String(page);c.syncRoute()}return{page,html:`<div class="report-pagination"><span id="report-count" role="status">${total.toLocaleString('pt-BR')} registros · página ${page} de ${pages}</span><div class="control-row"><button class="button small" data-report-page="${page-1}" ${page<=1?'disabled':''}>Página anterior</button><button class="button small" data-report-page="${page+1}" ${page>=pages?'disabled':''}>Próxima página</button></div></div>`}}
    function totals(rows){const valid=rows.filter(r=>r.valid),sum=field=>valid.reduce((s,r)=>s+(r[field]||0),0);return `<section id="report-totals" class="metrics"><div class="panel metric"><span class="label">Total válido dos pagamentos</span><span class="number">${c.fmtMoney(sum('amount')/100)}</span></div><div class="panel metric"><span class="label">${filters().reportClient?'Vinculado ao cliente selecionado':'Vinculado válido'}</span><span class="number">${c.fmtMoney(sum('share')/100)}</span></div><div class="panel metric"><span class="label">Livre dos pagamentos válidos</span><span class="number">${c.fmtMoney(sum('free')/100)}</span></div></section>`}
    function page(){if(!operational())return'<section class="panel panel-body"><h1>Acesso negado</h1></section>';const kind=filters().report;if(!kind)return head('Relatórios','Sete consultas dos registros fictícios. Valores mudam conforme cadastros, execução e pagamentos.')+`<div class="report-hub">${Object.entries(definitions).map(([id,d])=>`<a class="panel panel-body report-card" data-report-link="${id}" href="#relatorios?report=${id}"><h2>${esc(id==='aulas'?'Aulas':d.title)}</h2><p class="subtle">${esc(d.lead)}</p><span class="text-link">Abrir relatório →</span></a>`).join('')}</div>`;if(!Object.hasOwn(definitions,kind))return'<section class="panel panel-body"><h1>Relatório não encontrado</h1><a href="#relatorios">Voltar aos relatórios</a></section>';if(kind==='financeiro'&&!financial())return head('Relatório financeiro','Somente Dono e Administrativo podem consultar valores financeiros.')+'<p class="note">Somente Dono e Administrativo. Este perfil não recebe linhas ou exportação financeira.</p>';const def=definitions[kind],r=range(),rows=r.valid?queries[kind](filters(),r):[],pagination=pager(rows.length,20),visible=rows.slice((pagination.page-1)*20,pagination.page*20),keys=['reportFromDate','reportToDate',...def.filters.map(key=>({type:'reportType',instructor:'reportInstructor',status:'reportStatus',client:'reportClient',horse:'reportHorse',clientStatus:'reportClientStatus',campaign:'reportCampaign',reason:'reportReason',method:'reportMethod',purpose:'reportPurpose'}[key]))];return `<a class="text-link" href="#relatorios">← Relatórios</a>`+head(def.title,def.lead,`<button class="button primary" data-report-export="${kind}">Exportar CSV</button>`,'RELATÓRIOS · DADOS FICTÍCIOS')+filterPanel(reportFilters(kind),keys)+`<p id="report-note" class="note">${esc(notes[kind])} Período padrão: 30 dias até ${date(c.today)}, data da demonstração.</p><p id="report-message" role="alert">${r.valid?'':'Período inválido. Confira De e Até.'}</p>`+(kind==='financeiro'?totals(rows):'')+`<section class="panel">${pagination.html}${table([...def.columns.map(x=>x[1]),''],visible.map(row=>`<tr data-report-row="${esc(row.id)}">${def.columns.map(([key,,format])=>`<td data-column="${key}">${esc(display(row[key],format))}${key==='minutes'&&row.reference?' <small>(referência)</small>':''}</td>`).join('')}<td>${row.links.map(l=>`<button class="text-link" data-detail="${esc(l.kind)}:${esc(l.id)}">${esc(l.label)}</button>`).join('<br>')}</td></tr>`).join(''),'CSV inclui todo o recorte, até 1.000 registros; não apenas esta página.')}</section>`}
    function exportReport(kind){c.refresh();if(!operational()||!Object.hasOwn(definitions,kind)||kind==='financeiro'&&!financial()){notify('Acesso negado. Exportação indisponível.');return}const r=range(),message=$('#report-message');if(!r.valid){if(message)message.textContent='Período inválido. Confira De e Até.';return}const rows=queries[kind](filters(),r),def=definitions[kind];if(rows.length>1000){if(message)message.textContent=`Não é possível exportar ${rows.length.toLocaleString('pt-BR')} registros. Limite: 1.000. Ajuste os filtros.`;return}csv('ecobella-v2-relatorio-'+kind+'.csv',def.columns.map(x=>x[1]),rows.map(row=>def.columns.map(([key,,format])=>format==='money'?(row[key]/100).toFixed(2):key==='minutes'&&row.reference?display(row[key])+' (referência)':row[key])));if(message)message.textContent=`CSV gerado com ${rows.length} registros.`}
    function auditRows(r){const f=filters();return data().history.filter(x=>within(spDate(x.date),r)&&(!f.auditEntity||x.kind===f.auditEntity)&&(!f.auditRecord||x.recordId===f.auditRecord)&&(!f.auditAuthor||x.author===f.auditAuthor)).sort((a,b)=>b.date.localeCompare(a.date)||b.id.localeCompare(a.id))}
    function changed(x){const before=x.before||{},after=x.after||{};return unique([...Object.keys(before),...Object.keys(after)]).filter(k=>JSON.stringify(before[k])!==JSON.stringify(after[k]))}
    function auditPage(){if(!financial())return'<section class="panel panel-body"><h1>Acesso negado</h1><p>Auditoria geral disponível somente para Dono e Administrativo.</p></section>';const r=range(true),rows=r.valid?auditRows(r):[],pagination=pager(rows.length,15,true),f=filters(),content=dates('audit',f)+select('Tipo de registro','auditEntity',Object.entries(entityLabels))+`<label class="field">Registro<input class="input" data-report-filter="auditRecord" aria-label="Registro" value="${esc(f.auditRecord||'')}" placeholder="ID exato"></label>`+select('Autor','auditAuthor',unique(data().history.map(x=>x.author)).sort().map(x=>[x,x]));return head('Trilha de auditoria','Eventos fictícios gerados nesta demonstração; autor, horário de São Paulo, antes e depois.',`<button class="button primary" data-audit-export>Exportar CSV</button>`,'AUDITORIA · SIMULAÇÃO LOCAL')+filterPanel(content,['auditFromDate','auditToDate','auditEntity','auditRecord','auditAuthor'])+`<p class="note">Nenhum evento histórico é inventado. Período padrão: 30 dias até ${date(now())}, data atual de São Paulo.</p><p id="report-message" role="alert">${r.valid?'':'Período inválido. Confira De e Até.'}</p><section class="panel">${pagination.html}${table(['Quando','Autor','Registro','Ação','Antes / depois',''],rows.slice((pagination.page-1)*15,pagination.page*15).map(x=>`<tr data-audit-event="${esc(x.id)}"><td>${esc(stamp(x.date))}</td><td>${esc(x.author||'Não informado')}</td><td>${esc(entityLabels[x.kind]||x.kind)}<span class="secondary">${esc(x.recordId)}</span></td><td>${esc(x.action)}</td><td><details><summary>Ver ${changed(x).length} campos alterados</summary><p>Antes</p><pre class="class-audit">${esc(JSON.stringify(x.before,null,2)??'Não informado')}</pre><p>Depois</p><pre class="class-audit">${esc(JSON.stringify(x.after,null,2)??'Não informado')}</pre></details></td><td>${['client','class','payment','horse','team','campaign'].includes(x.kind)?`<button class="text-link" data-detail="${esc(x.kind)}:${esc(x.recordId)}">Abrir registro</button>`:''}<button class="text-link" data-audit-record="${esc(x.recordId)}" data-audit-kind="${esc(x.kind)}">Só este registro</button></td></tr>`).join(''),'CSV inclui todo o recorte autorizado, até 1.000 eventos.')}</section>`}
    function exportAudit(){c.refresh();if(!financial()){notify('Acesso negado. Auditoria indisponível.');return}const r=range(true),message=$('#report-message');if(!r.valid){if(message)message.textContent='Período inválido. Confira De e Até.';return}const rows=auditRows(r);if(rows.length>1000){if(message)message.textContent=`Não é possível exportar ${rows.length.toLocaleString('pt-BR')} eventos. Limite: 1.000. Ajuste os filtros.`;return}csv('ecobella-v2-auditoria.csv',['Quando','Autor','Entidade','Registro','Ação','Campos alterados','Resumo'],rows.map(x=>[stamp(x.date),x.author,entityLabels[x.kind]||x.kind,x.recordId,x.action,changed(x).join(', '),x.action]));if(message)message.textContent=`CSV gerado com ${rows.length} eventos.`}
    document.addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;if(b.dataset.reportExport)exportReport(b.dataset.reportExport);if(b.hasAttribute('data-audit-export'))exportAudit();if(b.dataset.reportPage){if(c.pageName()==='relatorios'&&operational()||c.pageName()==='auditoria'&&financial()){const key=c.pageName()==='auditoria'?'auditPage':'reportPage';route(c.pageName(),{...filters(),[key]:b.dataset.reportPage})}}if(b.dataset.auditRecord&&financial()){route('auditoria',{...filters(),auditEntity:b.dataset.auditKind,auditRecord:b.dataset.auditRecord,auditPage:'1'})}});
    document.addEventListener('input',e=>{const el=e.target,key=el.dataset.reportFilter;if(!key)return;const f=filters();f[key]=el.value;delete f.reportPage;delete f.auditPage;if(key==='auditEntity')delete f.auditRecord;const pos=el.selectionStart;render();const replacement=$(`[data-report-filter="${CSS.escape(key)}"]`);replacement?.focus();if(el.type==='text'&&pos!=null)replacement?.setSelectionRange(pos,pos)});
    return{page,auditPage};
  }
  globalThis.EcobellaReports={install};
})();
